
package nc.oa.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "NCService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.18.128.25/Webmobile3/Allserver/Ncs2019/NCService.asmx?wsdl")
@WebServiceClient(name = "NCService", targetNamespace = "http://tempuri.org/", wsdlLocation = "")
public class NCService
    extends Service
{

    private final static URL NCSERVICE_WSDL_LOCATION;
    private final static WebServiceException NCSERVICE_EXCEPTION;
    private final static QName NCSERVICE_QNAME = new QName("http://tempuri.org/", "NCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://172.18.128.25/Webmobile3/Allserver/Ncs2019/NCService.asmx?wsdl");
            url = new URL("");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NCSERVICE_WSDL_LOCATION = url;
        NCSERVICE_EXCEPTION = e;
    }

    public NCService() {
        super(__getWsdlLocation(), NCSERVICE_QNAME);
    }

    public NCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NCSERVICE_QNAME, features);
    }

    public NCService(URL wsdlLocation) {
        super(wsdlLocation, NCSERVICE_QNAME);
    }

    public NCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NCSERVICE_QNAME, features);
    }

    public NCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NCServiceSoap
     */
    @WebEndpoint(name = "NCServiceSoap")
    public NCServiceSoap getNCServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "NCServiceSoap"), NCServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NCServiceSoap
     */
    @WebEndpoint(name = "NCServiceSoap")
    public NCServiceSoap getNCServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "NCServiceSoap"), NCServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NCSERVICE_EXCEPTION!= null) {
            throw NCSERVICE_EXCEPTION;
        }
        return NCSERVICE_WSDL_LOCATION;
    }

}
