/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.pm.feebalance;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> �ڴ˴���Ҫ��������Ĺ��� </b>
 * <p>
 *     �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PmFeebalanceHVO extends SuperVO {
	private java.lang.String pm_feebalance;
	private java.lang.String bill_code;
	private java.lang.String bill_name;
	private java.lang.String pk_supplier_name;
	private java.lang.String pk_dkdept;
	private java.lang.String pk_dkdept_v;
	private java.lang.String pk_qydept;
	private java.lang.String pk_qydept_v;
	private nc.vo.pub.lang.UFDouble contractmoney;
	private nc.vo.pub.lang.UFDate signdate;
	private java.lang.String contracttype;
	private java.lang.String pk_lead_name;
	private java.lang.String pk_manager_name;
	private java.lang.String zbmethod;
	private nc.vo.pub.lang.UFDate startdate;
	private nc.vo.pub.lang.UFDate enddate;
	private java.lang.String pk_signer;
	private java.lang.String pk_signer_name;
	private java.lang.String vmemo;
	private java.lang.Integer fstatusflag;
	private nc.vo.pub.lang.UFDouble protocontractmoney;
	private nc.vo.pub.lang.UFDouble paymoney;
	private nc.vo.pub.lang.UFDouble addpaymoney;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.String def11;
	private java.lang.String def12;
	private java.lang.String def13;
	private java.lang.String def14;
	private java.lang.String def15;
	private java.lang.String def16;
	private java.lang.String def17;
	private java.lang.String def18;
	private java.lang.String def19;
	private java.lang.String def20;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_org_v;
	private java.lang.String bill_type;
	private java.lang.String billmaker;
	private nc.vo.pub.lang.UFDate billmaketime;
	private nc.vo.pub.lang.UFDate dbilldate;
	private java.lang.String auditor;
	private nc.vo.pub.lang.UFDateTime audittime;
	private java.lang.String check_opinion;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_transitype;
	private java.lang.String transitypecode;
	private java.lang.String pk_bill_type;
	private nc.vo.pub.lang.UFDouble version;
	private java.lang.String pk_contr;
	private java.lang.String def21;
	private java.lang.String def22;
	private java.lang.String def23;
	private java.lang.String def24;
	private java.lang.String def25;
	private java.lang.String def26;
	private java.lang.String def27;
	private java.lang.String def28;
	private java.lang.String def29;
	private java.lang.String def30;
	private java.lang.String def31;
	private java.lang.String def32;
	private java.lang.String def33;
	private java.lang.String def34;
	private java.lang.String def35;
	private java.lang.String def36;
	private java.lang.String def37;
	private java.lang.String def38;
	private java.lang.String def39;
	private java.lang.String def40;
	private java.lang.String def41;
	private java.lang.String def42;
	private java.lang.String def43;
	private java.lang.String def44;
	private java.lang.String def45;
	private java.lang.String def46;
	private java.lang.String def47;
	private java.lang.String def48;
	private java.lang.String def49;
	private java.lang.String def50;
	private java.lang.String def51;
	private java.lang.String def52;
	private java.lang.String def53;
	private java.lang.String def54;
	private java.lang.String def55;
	private java.lang.String def56;
	private java.lang.String def57;
	private java.lang.String def58;
	private java.lang.String def59;
	private java.lang.String def60;
	private java.lang.String def61;
	private java.lang.String def62;
	private java.lang.String def63;
	private java.lang.String def64;
	private java.lang.String def65;
	private java.lang.String def66;
	private java.lang.String def67;
	private java.lang.String def68;
	private java.lang.String def69;
	private java.lang.String def70;
	private java.lang.String def71;
	private java.lang.String def72;
	private java.lang.String def73;
	private java.lang.String def74;
	private java.lang.String def75;
	private java.lang.String def76;
	private java.lang.String def77;
	private java.lang.String def78;
	private java.lang.String def79;
	private java.lang.String def80;
	private java.lang.String def81;
	private java.lang.String def82;
	private java.lang.String def83;
	private java.lang.String def84;
	private java.lang.String def85;
	private java.lang.String def86;
	private java.lang.String def87;
	private java.lang.String def88;
	private java.lang.String def89;
	private java.lang.String def90;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PM_FEEBALANCE = "pm_feebalance";
	public static final String BILL_CODE = "bill_code";
	public static final String BILL_NAME = "bill_name";
	public static final String PK_SUPPLIER_NAME = "pk_supplier_name";
	public static final String PK_DKDEPT = "pk_dkdept";
	public static final String PK_DKDEPT_V = "pk_dkdept_v";
	public static final String PK_QYDEPT = "pk_qydept";
	public static final String PK_QYDEPT_V = "pk_qydept_v";
	public static final String CONTRACTMONEY = "contractmoney";
	public static final String SIGNDATE = "signdate";
	public static final String CONTRACTTYPE = "contracttype";
	public static final String PK_LEAD_NAME = "pk_lead_name";
	public static final String PK_MANAGER_NAME = "pk_manager_name";
	public static final String ZBMETHOD = "zbmethod";
	public static final String STARTDATE = "startdate";
	public static final String ENDDATE = "enddate";
	public static final String PK_SIGNER = "pk_signer";
	public static final String PK_SIGNER_NAME = "pk_signer_name";
	public static final String VMEMO = "vmemo";
	public static final String FSTATUSFLAG = "fstatusflag";
	public static final String PROTOCONTRACTMONEY = "protocontractmoney";
	public static final String PAYMONEY = "paymoney";
	public static final String ADDPAYMONEY = "addpaymoney";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
	public static final String DEF16 = "def16";
	public static final String DEF17 = "def17";
	public static final String DEF18 = "def18";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String BILL_TYPE = "bill_type";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKETIME = "billmaketime";
	public static final String DBILLDATE = "dbilldate";
	public static final String AUDITOR = "auditor";
	public static final String AUDITTIME = "audittime";
	public static final String CHECK_OPINION = "check_opinion";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_TRANSITYPE = "pk_transitype";
	public static final String TRANSITYPECODE = "transitypecode";
	public static final String PK_BILL_TYPE = "pk_bill_type";
	public static final String VERSION = "version";
	public static final String PK_CONTR = "pk_contr";
	public static final String DEF21 = "def21";
	public static final String DEF22 = "def22";
	public static final String DEF23 = "def23";
	public static final String DEF24 = "def24";
	public static final String DEF25 = "def25";
	public static final String DEF26 = "def26";
	public static final String DEF27 = "def27";
	public static final String DEF28 = "def28";
	public static final String DEF29 = "def29";
	public static final String DEF30 = "def30";
	public static final String DEF31 = "def31";
	public static final String DEF32 = "def32";
	public static final String DEF33 = "def33";
	public static final String DEF34 = "def34";
	public static final String DEF35 = "def35";
	public static final String DEF36 = "def36";
	public static final String DEF37 = "def37";
	public static final String DEF38 = "def38";
	public static final String DEF39 = "def39";
	public static final String DEF40 = "def40";
	public static final String DEF41 = "def41";
	public static final String DEF42 = "def42";
	public static final String DEF43 = "def43";
	public static final String DEF44 = "def44";
	public static final String DEF45 = "def45";
	public static final String DEF46 = "def46";
	public static final String DEF47 = "def47";
	public static final String DEF48 = "def48";
	public static final String DEF49 = "def49";
	public static final String DEF50 = "def50";
	public static final String DEF51 = "def51";
	public static final String DEF52 = "def52";
	public static final String DEF53 = "def53";
	public static final String DEF54 = "def54";
	public static final String DEF55 = "def55";
	public static final String DEF56 = "def56";
	public static final String DEF57 = "def57";
	public static final String DEF58 = "def58";
	public static final String DEF59 = "def59";
	public static final String DEF60 = "def60";
	public static final String DEF61 = "def61";
	public static final String DEF62 = "def62";
	public static final String DEF63 = "def63";
	public static final String DEF64 = "def64";
	public static final String DEF65 = "def65";
	public static final String DEF66 = "def66";
	public static final String DEF67 = "def67";
	public static final String DEF68 = "def68";
	public static final String DEF69 = "def69";
	public static final String DEF70 = "def70";
	public static final String DEF71 = "def71";
	public static final String DEF72 = "def72";
	public static final String DEF73 = "def73";
	public static final String DEF74 = "def74";
	public static final String DEF75 = "def75";
	public static final String DEF76 = "def76";
	public static final String DEF77 = "def77";
	public static final String DEF78 = "def78";
	public static final String DEF79 = "def79";
	public static final String DEF80 = "def80";
	public static final String DEF81 = "def81";
	public static final String DEF82 = "def82";
	public static final String DEF83 = "def83";
	public static final String DEF84 = "def84";
	public static final String DEF85 = "def85";
	public static final String DEF86 = "def86";
	public static final String DEF87 = "def87";
	public static final String DEF88 = "def88";
	public static final String DEF89 = "def89";
	public static final String DEF90 = "def90";
			
	/**
	 * ����pm_feebalance��Getter����.����������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPm_feebalance () {
		return pm_feebalance;
	}   
	/**
	 * ����pm_feebalance��Setter����.����������������
	 * ��������:
	 * @param newPm_feebalance java.lang.String
	 */
	public void setPm_feebalance (java.lang.String newPm_feebalance ) {
	 	this.pm_feebalance = newPm_feebalance;
	} 	  
	/**
	 * ����bill_code��Getter����.����������ͬ���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getBill_code () {
		return bill_code;
	}   
	/**
	 * ����bill_code��Setter����.����������ͬ���
	 * ��������:
	 * @param newBill_code java.lang.String
	 */
	public void setBill_code (java.lang.String newBill_code ) {
	 	this.bill_code = newBill_code;
	} 	  
	/**
	 * ����bill_name��Getter����.����������ͬ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getBill_name () {
		return bill_name;
	}   
	/**
	 * ����bill_name��Setter����.����������ͬ����
	 * ��������:
	 * @param newBill_name java.lang.String
	 */
	public void setBill_name (java.lang.String newBill_name ) {
	 	this.bill_name = newBill_name;
	} 	  
	/**
	 * ����pk_supplier_name��Getter����.����������Ӧ������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_supplier_name () {
		return pk_supplier_name;
	}   
	/**
	 * ����pk_supplier_name��Setter����.����������Ӧ������
	 * ��������:
	 * @param newPk_supplier_name java.lang.String
	 */
	public void setPk_supplier_name (java.lang.String newPk_supplier_name ) {
	 	this.pk_supplier_name = newPk_supplier_name;
	} 	  
	/**
	 * ����pk_dkdept��Getter����.�����������ز���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dkdept () {
		return pk_dkdept;
	}   
	/**
	 * ����pk_dkdept��Setter����.�����������ز���
	 * ��������:
	 * @param newPk_dkdept java.lang.String
	 */
	public void setPk_dkdept (java.lang.String newPk_dkdept ) {
	 	this.pk_dkdept = newPk_dkdept;
	} 	  
	/**
	 * ����pk_dkdept_v��Getter����.�����������ز��Ű汾��Ϣ
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dkdept_v () {
		return pk_dkdept_v;
	}   
	/**
	 * ����pk_dkdept_v��Setter����.�����������ز��Ű汾��Ϣ
	 * ��������:
	 * @param newPk_dkdept_v java.lang.String
	 */
	public void setPk_dkdept_v (java.lang.String newPk_dkdept_v ) {
	 	this.pk_dkdept_v = newPk_dkdept_v;
	} 	  
	/**
	 * ����pk_qydept��Getter����.��������ǩԼ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_qydept () {
		return pk_qydept;
	}   
	/**
	 * ����pk_qydept��Setter����.��������ǩԼ����
	 * ��������:
	 * @param newPk_qydept java.lang.String
	 */
	public void setPk_qydept (java.lang.String newPk_qydept ) {
	 	this.pk_qydept = newPk_qydept;
	} 	  
	/**
	 * ����pk_qydept_v��Getter����.��������ǩԼ���Ű汾��Ϣ
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_qydept_v () {
		return pk_qydept_v;
	}   
	/**
	 * ����pk_qydept_v��Setter����.��������ǩԼ���Ű汾��Ϣ
	 * ��������:
	 * @param newPk_qydept_v java.lang.String
	 */
	public void setPk_qydept_v (java.lang.String newPk_qydept_v ) {
	 	this.pk_qydept_v = newPk_qydept_v;
	} 	  
	/**
	 * ����contractmoney��Getter����.����������ͬ���
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getContractmoney () {
		return contractmoney;
	}   
	/**
	 * ����contractmoney��Setter����.����������ͬ���
	 * ��������:
	 * @param newContractmoney nc.vo.pub.lang.UFDouble
	 */
	public void setContractmoney (nc.vo.pub.lang.UFDouble newContractmoney ) {
	 	this.contractmoney = newContractmoney;
	} 	  
	/**
	 * ����signdate��Getter����.��������ǩԼ����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getSigndate () {
		return signdate;
	}   
	/**
	 * ����signdate��Setter����.��������ǩԼ����
	 * ��������:
	 * @param newSigndate nc.vo.pub.lang.UFDate
	 */
	public void setSigndate (nc.vo.pub.lang.UFDate newSigndate ) {
	 	this.signdate = newSigndate;
	} 	  
	/**
	 * ����contracttype��Getter����.����������ͬ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getContracttype () {
		return contracttype;
	}   
	/**
	 * ����contracttype��Setter����.����������ͬ����
	 * ��������:
	 * @param newContracttype java.lang.String
	 */
	public void setContracttype (java.lang.String newContracttype ) {
	 	this.contracttype = newContracttype;
	} 	  
	/**
	 * ����pk_lead_name��Getter����.���������ֹ��쵼����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_lead_name () {
		return pk_lead_name;
	}   
	/**
	 * ����pk_lead_name��Setter����.���������ֹ��쵼����
	 * ��������:
	 * @param newPk_lead_name java.lang.String
	 */
	public void setPk_lead_name (java.lang.String newPk_lead_name ) {
	 	this.pk_lead_name = newPk_lead_name;
	} 	  
	/**
	 * ����pk_manager_name��Getter����.����������Ŀ��������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_manager_name () {
		return pk_manager_name;
	}   
	/**
	 * ����pk_manager_name��Setter����.����������Ŀ��������
	 * ��������:
	 * @param newPk_manager_name java.lang.String
	 */
	public void setPk_manager_name (java.lang.String newPk_manager_name ) {
	 	this.pk_manager_name = newPk_manager_name;
	} 	  
	/**
	 * ����zbmethod��Getter����.���������б귽ʽ
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getZbmethod () {
		return zbmethod;
	}   
	/**
	 * ����zbmethod��Setter����.���������б귽ʽ
	 * ��������:
	 * @param newZbmethod java.lang.String
	 */
	public void setZbmethod (java.lang.String newZbmethod ) {
	 	this.zbmethod = newZbmethod;
	} 	  
	/**
	 * ����startdate��Getter����.����������ʼ����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getStartdate () {
		return startdate;
	}   
	/**
	 * ����startdate��Setter����.����������ʼ����
	 * ��������:
	 * @param newStartdate nc.vo.pub.lang.UFDate
	 */
	public void setStartdate (nc.vo.pub.lang.UFDate newStartdate ) {
	 	this.startdate = newStartdate;
	} 	  
	/**
	 * ����enddate��Getter����.����������������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getEnddate () {
		return enddate;
	}   
	/**
	 * ����enddate��Setter����.����������������
	 * ��������:
	 * @param newEnddate nc.vo.pub.lang.UFDate
	 */
	public void setEnddate (nc.vo.pub.lang.UFDate newEnddate ) {
	 	this.enddate = newEnddate;
	} 	  
	/**
	 * ����pk_signer��Getter����.��������ǩԼ������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_signer () {
		return pk_signer;
	}   
	/**
	 * ����pk_signer��Setter����.��������ǩԼ������
	 * ��������:
	 * @param newPk_signer java.lang.String
	 */
	public void setPk_signer (java.lang.String newPk_signer ) {
	 	this.pk_signer = newPk_signer;
	} 	  
	/**
	 * ����pk_signer_name��Getter����.��������ǩԼ������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_signer_name () {
		return pk_signer_name;
	}   
	/**
	 * ����pk_signer_name��Setter����.��������ǩԼ������
	 * ��������:
	 * @param newPk_signer_name java.lang.String
	 */
	public void setPk_signer_name (java.lang.String newPk_signer_name ) {
	 	this.pk_signer_name = newPk_signer_name;
	} 	  
	/**
	 * ����vmemo��Getter����.����������ע
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getVmemo () {
		return vmemo;
	}   
	/**
	 * ����vmemo��Setter����.����������ע
	 * ��������:
	 * @param newVmemo java.lang.String
	 */
	public void setVmemo (java.lang.String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * ����fstatusflag��Getter����.������������״̬
	 * ��������:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getFstatusflag () {
		return fstatusflag;
	}   
	/**
	 * ����fstatusflag��Setter����.������������״̬
	 * ��������:
	 * @param newFstatusflag java.lang.Integer
	 */
	public void setFstatusflag (java.lang.Integer newFstatusflag ) {
	 	this.fstatusflag = newFstatusflag;
	} 	  
	/**
	 * ����protocontractmoney��Getter����.��������ԭ��ͬ���
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getProtocontractmoney () {
		return protocontractmoney;
	}   
	/**
	 * ����protocontractmoney��Setter����.��������ԭ��ͬ���
	 * ��������:
	 * @param newProtocontractmoney nc.vo.pub.lang.UFDouble
	 */
	public void setProtocontractmoney (nc.vo.pub.lang.UFDouble newProtocontractmoney ) {
	 	this.protocontractmoney = newProtocontractmoney;
	} 	  
	/**
	 * ����paymoney��Getter����.���������Ѹ�����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getPaymoney () {
		return paymoney;
	}   
	/**
	 * ����paymoney��Setter����.���������Ѹ�����
	 * ��������:
	 * @param newPaymoney nc.vo.pub.lang.UFDouble
	 */
	public void setPaymoney (nc.vo.pub.lang.UFDouble newPaymoney ) {
	 	this.paymoney = newPaymoney;
	} 	  
	/**
	 * ����addpaymoney��Getter����.���������ۼƸ�����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getAddpaymoney () {
		return addpaymoney;
	}   
	/**
	 * ����addpaymoney��Setter����.���������ۼƸ�����
	 * ��������:
	 * @param newAddpaymoney nc.vo.pub.lang.UFDouble
	 */
	public void setAddpaymoney (nc.vo.pub.lang.UFDouble newAddpaymoney ) {
	 	this.addpaymoney = newAddpaymoney;
	} 	  
	/**
	 * ����def1��Getter����.���������Զ�����1
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * ����def1��Setter����.���������Զ�����1
	 * ��������:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * ����def2��Getter����.���������Զ�����2
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * ����def2��Setter����.���������Զ�����2
	 * ��������:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * ����def3��Getter����.���������Զ�����3
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * ����def3��Setter����.���������Զ�����3
	 * ��������:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * ����def4��Getter����.���������Զ�����4
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * ����def4��Setter����.���������Զ�����4
	 * ��������:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * ����def5��Getter����.���������Զ�����5
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * ����def5��Setter����.���������Զ�����5
	 * ��������:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * ����def6��Getter����.���������Զ�����6
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * ����def6��Setter����.���������Զ�����6
	 * ��������:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * ����def7��Getter����.���������Զ�����7
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * ����def7��Setter����.���������Զ�����7
	 * ��������:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * ����def8��Getter����.���������Զ�����8
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * ����def8��Setter����.���������Զ�����8
	 * ��������:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * ����def9��Getter����.���������Զ�����9
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * ����def9��Setter����.���������Զ�����9
	 * ��������:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * ����def10��Getter����.���������Զ�����10
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * ����def10��Setter����.���������Զ�����10
	 * ��������:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * ����def11��Getter����.���������Զ�����11
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef11 () {
		return def11;
	}   
	/**
	 * ����def11��Setter����.���������Զ�����11
	 * ��������:
	 * @param newDef11 java.lang.String
	 */
	public void setDef11 (java.lang.String newDef11 ) {
	 	this.def11 = newDef11;
	} 	  
	/**
	 * ����def12��Getter����.���������Զ�����12
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef12 () {
		return def12;
	}   
	/**
	 * ����def12��Setter����.���������Զ�����12
	 * ��������:
	 * @param newDef12 java.lang.String
	 */
	public void setDef12 (java.lang.String newDef12 ) {
	 	this.def12 = newDef12;
	} 	  
	/**
	 * ����def13��Getter����.���������Զ�����13
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef13 () {
		return def13;
	}   
	/**
	 * ����def13��Setter����.���������Զ�����13
	 * ��������:
	 * @param newDef13 java.lang.String
	 */
	public void setDef13 (java.lang.String newDef13 ) {
	 	this.def13 = newDef13;
	} 	  
	/**
	 * ����def14��Getter����.���������Զ�����14
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef14 () {
		return def14;
	}   
	/**
	 * ����def14��Setter����.���������Զ�����14
	 * ��������:
	 * @param newDef14 java.lang.String
	 */
	public void setDef14 (java.lang.String newDef14 ) {
	 	this.def14 = newDef14;
	} 	  
	/**
	 * ����def15��Getter����.���������Զ�����15
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef15 () {
		return def15;
	}   
	/**
	 * ����def15��Setter����.���������Զ�����15
	 * ��������:
	 * @param newDef15 java.lang.String
	 */
	public void setDef15 (java.lang.String newDef15 ) {
	 	this.def15 = newDef15;
	} 	  
	/**
	 * ����def16��Getter����.���������Զ�����16
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef16 () {
		return def16;
	}   
	/**
	 * ����def16��Setter����.���������Զ�����16
	 * ��������:
	 * @param newDef16 java.lang.String
	 */
	public void setDef16 (java.lang.String newDef16 ) {
	 	this.def16 = newDef16;
	} 	  
	/**
	 * ����def17��Getter����.���������Զ�����17
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef17 () {
		return def17;
	}   
	/**
	 * ����def17��Setter����.���������Զ�����17
	 * ��������:
	 * @param newDef17 java.lang.String
	 */
	public void setDef17 (java.lang.String newDef17 ) {
	 	this.def17 = newDef17;
	} 	  
	/**
	 * ����def18��Getter����.���������Զ�����18
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef18 () {
		return def18;
	}   
	/**
	 * ����def18��Setter����.���������Զ�����18
	 * ��������:
	 * @param newDef18 java.lang.String
	 */
	public void setDef18 (java.lang.String newDef18 ) {
	 	this.def18 = newDef18;
	} 	  
	/**
	 * ����def19��Getter����.���������Զ�����19
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef19 () {
		return def19;
	}   
	/**
	 * ����def19��Setter����.���������Զ�����19
	 * ��������:
	 * @param newDef19 java.lang.String
	 */
	public void setDef19 (java.lang.String newDef19 ) {
	 	this.def19 = newDef19;
	} 	  
	/**
	 * ����def20��Getter����.���������Զ�����20
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef20 () {
		return def20;
	}   
	/**
	 * ����def20��Setter����.���������Զ�����20
	 * ��������:
	 * @param newDef20 java.lang.String
	 */
	public void setDef20 (java.lang.String newDef20 ) {
	 	this.def20 = newDef20;
	} 	  
	/**
	 * ����pk_group��Getter����.������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * ����pk_group��Setter����.������������
	 * ��������:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * ����pk_org��Getter����.����������Ŀ��֯
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * ����pk_org��Setter����.����������Ŀ��֯
	 * ��������:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * ����pk_org_v��Getter����.����������Ŀ��֯���°汾
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v () {
		return pk_org_v;
	}   
	/**
	 * ����pk_org_v��Setter����.����������Ŀ��֯���°汾
	 * ��������:
	 * @param newPk_org_v java.lang.String
	 */
	public void setPk_org_v (java.lang.String newPk_org_v ) {
	 	this.pk_org_v = newPk_org_v;
	} 	  
	/**
	 * ����bill_type��Getter����.����������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getBill_type () {
		return bill_type;
	}   
	/**
	 * ����bill_type��Setter����.����������������
	 * ��������:
	 * @param newBill_type java.lang.String
	 */
	public void setBill_type (java.lang.String newBill_type ) {
	 	this.bill_type = newBill_type;
	} 	  
	/**
	 * ����billmaker��Getter����.���������Ƶ���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}   
	/**
	 * ����billmaker��Setter����.���������Ƶ���
	 * ��������:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	this.billmaker = newBillmaker;
	} 	  
	/**
	 * ����billmaketime��Getter����.���������Ƶ�����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getBillmaketime () {
		return billmaketime;
	}   
	/**
	 * ����billmaketime��Setter����.���������Ƶ�����
	 * ��������:
	 * @param newBillmaketime nc.vo.pub.lang.UFDate
	 */
	public void setBillmaketime (nc.vo.pub.lang.UFDate newBillmaketime ) {
	 	this.billmaketime = newBillmaketime;
	} 	  
	/**
	 * ����dbilldate��Getter����.����������������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDbilldate () {
		return dbilldate;
	}   
	/**
	 * ����dbilldate��Setter����.����������������
	 * ��������:
	 * @param newDbilldate nc.vo.pub.lang.UFDate
	 */
	public void setDbilldate (nc.vo.pub.lang.UFDate newDbilldate ) {
	 	this.dbilldate = newDbilldate;
	} 	  
	/**
	 * ����auditor��Getter����.��������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getAuditor () {
		return auditor;
	}   
	/**
	 * ����auditor��Setter����.��������������
	 * ��������:
	 * @param newAuditor java.lang.String
	 */
	public void setAuditor (java.lang.String newAuditor ) {
	 	this.auditor = newAuditor;
	} 	  
	/**
	 * ����audittime��Getter����.����������������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getAudittime () {
		return audittime;
	}   
	/**
	 * ����audittime��Setter����.����������������
	 * ��������:
	 * @param newAudittime nc.vo.pub.lang.UFDateTime
	 */
	public void setAudittime (nc.vo.pub.lang.UFDateTime newAudittime ) {
	 	this.audittime = newAudittime;
	} 	  
	/**
	 * ����check_opinion��Getter����.���������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCheck_opinion () {
		return check_opinion;
	}   
	/**
	 * ����check_opinion��Setter����.���������������
	 * ��������:
	 * @param newCheck_opinion java.lang.String
	 */
	public void setCheck_opinion (java.lang.String newCheck_opinion ) {
	 	this.check_opinion = newCheck_opinion;
	} 	  
	/**
	 * ����creator��Getter����.��������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * ����creator��Setter����.��������������
	 * ��������:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * ����creationtime��Getter����.������������ʱ��
	 * ��������:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * ����creationtime��Setter����.������������ʱ��
	 * ��������:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * ����modifier��Getter����.������������޸���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * ����modifier��Setter����.������������޸���
	 * ��������:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * ����modifiedtime��Getter����.������������޸�ʱ��
	 * ��������:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * ����modifiedtime��Setter����.������������޸�ʱ��
	 * ��������:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * ����pk_transitype��Getter����.����������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_transitype () {
		return pk_transitype;
	}   
	/**
	 * ����pk_transitype��Setter����.����������������
	 * ��������:
	 * @param newPk_transitype java.lang.String
	 */
	public void setPk_transitype (java.lang.String newPk_transitype ) {
	 	this.pk_transitype = newPk_transitype;
	} 	  
	/**
	 * ����transitypecode��Getter����.���������������ͱ���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getTransitypecode () {
		return transitypecode;
	}   
	/**
	 * ����transitypecode��Setter����.���������������ͱ���
	 * ��������:
	 * @param newTransitypecode java.lang.String
	 */
	public void setTransitypecode (java.lang.String newTransitypecode ) {
	 	this.transitypecode = newTransitypecode;
	} 	  
	/**
	 * ����pk_bill_type��Getter����.��������������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bill_type () {
		return pk_bill_type;
	}   
	/**
	 * ����pk_bill_type��Setter����.��������������������
	 * ��������:
	 * @param newPk_bill_type java.lang.String
	 */
	public void setPk_bill_type (java.lang.String newPk_bill_type ) {
	 	this.pk_bill_type = newPk_bill_type;
	} 	  
	/**
	 * ����version��Getter����.���������汾��
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVersion () {
		return version;
	}   
	/**
	 * ����version��Setter����.���������汾��
	 * ��������:
	 * @param newVersion nc.vo.pub.lang.UFDouble
	 */
	public void setVersion (nc.vo.pub.lang.UFDouble newVersion ) {
	 	this.version = newVersion;
	} 	  
	/**
	 * ����pk_contr��Getter����.����������ͬ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_contr () {
		return pk_contr;
	}   
	/**
	 * ����pk_contr��Setter����.����������ͬ����
	 * ��������:
	 * @param newPk_contr java.lang.String
	 */
	public void setPk_contr (java.lang.String newPk_contr ) {
	 	this.pk_contr = newPk_contr;
	} 	  
	/**
	 * ����def21��Getter����.���������Զ�����21
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef21 () {
		return def21;
	}   
	/**
	 * ����def21��Setter����.���������Զ�����21
	 * ��������:
	 * @param newDef21 java.lang.String
	 */
	public void setDef21 (java.lang.String newDef21 ) {
	 	this.def21 = newDef21;
	} 	  
	/**
	 * ����def22��Getter����.���������Զ�����22
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef22 () {
		return def22;
	}   
	/**
	 * ����def22��Setter����.���������Զ�����22
	 * ��������:
	 * @param newDef22 java.lang.String
	 */
	public void setDef22 (java.lang.String newDef22 ) {
	 	this.def22 = newDef22;
	} 	  
	/**
	 * ����def23��Getter����.���������Զ�����23
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef23 () {
		return def23;
	}   
	/**
	 * ����def23��Setter����.���������Զ�����23
	 * ��������:
	 * @param newDef23 java.lang.String
	 */
	public void setDef23 (java.lang.String newDef23 ) {
	 	this.def23 = newDef23;
	} 	  
	/**
	 * ����def24��Getter����.���������Զ�����24
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef24 () {
		return def24;
	}   
	/**
	 * ����def24��Setter����.���������Զ�����24
	 * ��������:
	 * @param newDef24 java.lang.String
	 */
	public void setDef24 (java.lang.String newDef24 ) {
	 	this.def24 = newDef24;
	} 	  
	/**
	 * ����def25��Getter����.���������Զ�����25
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef25 () {
		return def25;
	}   
	/**
	 * ����def25��Setter����.���������Զ�����25
	 * ��������:
	 * @param newDef25 java.lang.String
	 */
	public void setDef25 (java.lang.String newDef25 ) {
	 	this.def25 = newDef25;
	} 	  
	/**
	 * ����def26��Getter����.���������Զ�����26
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef26 () {
		return def26;
	}   
	/**
	 * ����def26��Setter����.���������Զ�����26
	 * ��������:
	 * @param newDef26 java.lang.String
	 */
	public void setDef26 (java.lang.String newDef26 ) {
	 	this.def26 = newDef26;
	} 	  
	/**
	 * ����def27��Getter����.���������Զ�����27
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef27 () {
		return def27;
	}   
	/**
	 * ����def27��Setter����.���������Զ�����27
	 * ��������:
	 * @param newDef27 java.lang.String
	 */
	public void setDef27 (java.lang.String newDef27 ) {
	 	this.def27 = newDef27;
	} 	  
	/**
	 * ����def28��Getter����.���������Զ�����28
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef28 () {
		return def28;
	}   
	/**
	 * ����def28��Setter����.���������Զ�����28
	 * ��������:
	 * @param newDef28 java.lang.String
	 */
	public void setDef28 (java.lang.String newDef28 ) {
	 	this.def28 = newDef28;
	} 	  
	/**
	 * ����def29��Getter����.���������Զ�����29
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef29 () {
		return def29;
	}   
	/**
	 * ����def29��Setter����.���������Զ�����29
	 * ��������:
	 * @param newDef29 java.lang.String
	 */
	public void setDef29 (java.lang.String newDef29 ) {
	 	this.def29 = newDef29;
	} 	  
	/**
	 * ����def30��Getter����.���������Զ�����30
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef30 () {
		return def30;
	}   
	/**
	 * ����def30��Setter����.���������Զ�����30
	 * ��������:
	 * @param newDef30 java.lang.String
	 */
	public void setDef30 (java.lang.String newDef30 ) {
	 	this.def30 = newDef30;
	} 	  
	/**
	 * ����def31��Getter����.���������Զ�����31
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef31 () {
		return def31;
	}   
	/**
	 * ����def31��Setter����.���������Զ�����31
	 * ��������:
	 * @param newDef31 java.lang.String
	 */
	public void setDef31 (java.lang.String newDef31 ) {
	 	this.def31 = newDef31;
	} 	  
	/**
	 * ����def32��Getter����.���������Զ�����32
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef32 () {
		return def32;
	}   
	/**
	 * ����def32��Setter����.���������Զ�����32
	 * ��������:
	 * @param newDef32 java.lang.String
	 */
	public void setDef32 (java.lang.String newDef32 ) {
	 	this.def32 = newDef32;
	} 	  
	/**
	 * ����def33��Getter����.���������Զ�����33
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef33 () {
		return def33;
	}   
	/**
	 * ����def33��Setter����.���������Զ�����33
	 * ��������:
	 * @param newDef33 java.lang.String
	 */
	public void setDef33 (java.lang.String newDef33 ) {
	 	this.def33 = newDef33;
	} 	  
	/**
	 * ����def34��Getter����.���������Զ�����34
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef34 () {
		return def34;
	}   
	/**
	 * ����def34��Setter����.���������Զ�����34
	 * ��������:
	 * @param newDef34 java.lang.String
	 */
	public void setDef34 (java.lang.String newDef34 ) {
	 	this.def34 = newDef34;
	} 	  
	/**
	 * ����def35��Getter����.���������Զ�����35
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef35 () {
		return def35;
	}   
	/**
	 * ����def35��Setter����.���������Զ�����35
	 * ��������:
	 * @param newDef35 java.lang.String
	 */
	public void setDef35 (java.lang.String newDef35 ) {
	 	this.def35 = newDef35;
	} 	  
	/**
	 * ����def36��Getter����.���������Զ�����36
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef36 () {
		return def36;
	}   
	/**
	 * ����def36��Setter����.���������Զ�����36
	 * ��������:
	 * @param newDef36 java.lang.String
	 */
	public void setDef36 (java.lang.String newDef36 ) {
	 	this.def36 = newDef36;
	} 	  
	/**
	 * ����def37��Getter����.���������Զ�����37
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef37 () {
		return def37;
	}   
	/**
	 * ����def37��Setter����.���������Զ�����37
	 * ��������:
	 * @param newDef37 java.lang.String
	 */
	public void setDef37 (java.lang.String newDef37 ) {
	 	this.def37 = newDef37;
	} 	  
	/**
	 * ����def38��Getter����.���������Զ�����38
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef38 () {
		return def38;
	}   
	/**
	 * ����def38��Setter����.���������Զ�����38
	 * ��������:
	 * @param newDef38 java.lang.String
	 */
	public void setDef38 (java.lang.String newDef38 ) {
	 	this.def38 = newDef38;
	} 	  
	/**
	 * ����def39��Getter����.���������Զ�����39
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef39 () {
		return def39;
	}   
	/**
	 * ����def39��Setter����.���������Զ�����39
	 * ��������:
	 * @param newDef39 java.lang.String
	 */
	public void setDef39 (java.lang.String newDef39 ) {
	 	this.def39 = newDef39;
	} 	  
	/**
	 * ����def40��Getter����.���������Զ�����40
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef40 () {
		return def40;
	}   
	/**
	 * ����def40��Setter����.���������Զ�����40
	 * ��������:
	 * @param newDef40 java.lang.String
	 */
	public void setDef40 (java.lang.String newDef40 ) {
	 	this.def40 = newDef40;
	} 	  
	/**
	 * ����def41��Getter����.���������Զ�����41
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef41 () {
		return def41;
	}   
	/**
	 * ����def41��Setter����.���������Զ�����41
	 * ��������:
	 * @param newDef41 java.lang.String
	 */
	public void setDef41 (java.lang.String newDef41 ) {
	 	this.def41 = newDef41;
	} 	  
	/**
	 * ����def42��Getter����.���������Զ�����42
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef42 () {
		return def42;
	}   
	/**
	 * ����def42��Setter����.���������Զ�����42
	 * ��������:
	 * @param newDef42 java.lang.String
	 */
	public void setDef42 (java.lang.String newDef42 ) {
	 	this.def42 = newDef42;
	} 	  
	/**
	 * ����def43��Getter����.���������Զ�����43
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef43 () {
		return def43;
	}   
	/**
	 * ����def43��Setter����.���������Զ�����43
	 * ��������:
	 * @param newDef43 java.lang.String
	 */
	public void setDef43 (java.lang.String newDef43 ) {
	 	this.def43 = newDef43;
	} 	  
	/**
	 * ����def44��Getter����.���������Զ�����44
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef44 () {
		return def44;
	}   
	/**
	 * ����def44��Setter����.���������Զ�����44
	 * ��������:
	 * @param newDef44 java.lang.String
	 */
	public void setDef44 (java.lang.String newDef44 ) {
	 	this.def44 = newDef44;
	} 	  
	/**
	 * ����def45��Getter����.���������Զ�����45
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef45 () {
		return def45;
	}   
	/**
	 * ����def45��Setter����.���������Զ�����45
	 * ��������:
	 * @param newDef45 java.lang.String
	 */
	public void setDef45 (java.lang.String newDef45 ) {
	 	this.def45 = newDef45;
	} 	  
	/**
	 * ����def46��Getter����.���������Զ�����46
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef46 () {
		return def46;
	}   
	/**
	 * ����def46��Setter����.���������Զ�����46
	 * ��������:
	 * @param newDef46 java.lang.String
	 */
	public void setDef46 (java.lang.String newDef46 ) {
	 	this.def46 = newDef46;
	} 	  
	/**
	 * ����def47��Getter����.���������Զ�����47
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef47 () {
		return def47;
	}   
	/**
	 * ����def47��Setter����.���������Զ�����47
	 * ��������:
	 * @param newDef47 java.lang.String
	 */
	public void setDef47 (java.lang.String newDef47 ) {
	 	this.def47 = newDef47;
	} 	  
	/**
	 * ����def48��Getter����.���������Զ�����48
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef48 () {
		return def48;
	}   
	/**
	 * ����def48��Setter����.���������Զ�����48
	 * ��������:
	 * @param newDef48 java.lang.String
	 */
	public void setDef48 (java.lang.String newDef48 ) {
	 	this.def48 = newDef48;
	} 	  
	/**
	 * ����def49��Getter����.���������Զ�����49
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef49 () {
		return def49;
	}   
	/**
	 * ����def49��Setter����.���������Զ�����49
	 * ��������:
	 * @param newDef49 java.lang.String
	 */
	public void setDef49 (java.lang.String newDef49 ) {
	 	this.def49 = newDef49;
	} 	  
	/**
	 * ����def50��Getter����.���������Զ�����50
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef50 () {
		return def50;
	}   
	/**
	 * ����def50��Setter����.���������Զ�����50
	 * ��������:
	 * @param newDef50 java.lang.String
	 */
	public void setDef50 (java.lang.String newDef50 ) {
	 	this.def50 = newDef50;
	} 	  
	/**
	 * ����def51��Getter����.���������Զ�����51
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef51 () {
		return def51;
	}   
	/**
	 * ����def51��Setter����.���������Զ�����51
	 * ��������:
	 * @param newDef51 java.lang.String
	 */
	public void setDef51 (java.lang.String newDef51 ) {
	 	this.def51 = newDef51;
	} 	  
	/**
	 * ����def52��Getter����.���������Զ�����52
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef52 () {
		return def52;
	}   
	/**
	 * ����def52��Setter����.���������Զ�����52
	 * ��������:
	 * @param newDef52 java.lang.String
	 */
	public void setDef52 (java.lang.String newDef52 ) {
	 	this.def52 = newDef52;
	} 	  
	/**
	 * ����def53��Getter����.���������Զ�����53
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef53 () {
		return def53;
	}   
	/**
	 * ����def53��Setter����.���������Զ�����53
	 * ��������:
	 * @param newDef53 java.lang.String
	 */
	public void setDef53 (java.lang.String newDef53 ) {
	 	this.def53 = newDef53;
	} 	  
	/**
	 * ����def54��Getter����.���������Զ�����54
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef54 () {
		return def54;
	}   
	/**
	 * ����def54��Setter����.���������Զ�����54
	 * ��������:
	 * @param newDef54 java.lang.String
	 */
	public void setDef54 (java.lang.String newDef54 ) {
	 	this.def54 = newDef54;
	} 	  
	/**
	 * ����def55��Getter����.���������Զ�����55
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef55 () {
		return def55;
	}   
	/**
	 * ����def55��Setter����.���������Զ�����55
	 * ��������:
	 * @param newDef55 java.lang.String
	 */
	public void setDef55 (java.lang.String newDef55 ) {
	 	this.def55 = newDef55;
	} 	  
	/**
	 * ����def56��Getter����.���������Զ�����56
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef56 () {
		return def56;
	}   
	/**
	 * ����def56��Setter����.���������Զ�����56
	 * ��������:
	 * @param newDef56 java.lang.String
	 */
	public void setDef56 (java.lang.String newDef56 ) {
	 	this.def56 = newDef56;
	} 	  
	/**
	 * ����def57��Getter����.���������Զ�����57
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef57 () {
		return def57;
	}   
	/**
	 * ����def57��Setter����.���������Զ�����57
	 * ��������:
	 * @param newDef57 java.lang.String
	 */
	public void setDef57 (java.lang.String newDef57 ) {
	 	this.def57 = newDef57;
	} 	  
	/**
	 * ����def58��Getter����.���������Զ�����58
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef58 () {
		return def58;
	}   
	/**
	 * ����def58��Setter����.���������Զ�����58
	 * ��������:
	 * @param newDef58 java.lang.String
	 */
	public void setDef58 (java.lang.String newDef58 ) {
	 	this.def58 = newDef58;
	} 	  
	/**
	 * ����def59��Getter����.���������Զ�����59
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef59 () {
		return def59;
	}   
	/**
	 * ����def59��Setter����.���������Զ�����59
	 * ��������:
	 * @param newDef59 java.lang.String
	 */
	public void setDef59 (java.lang.String newDef59 ) {
	 	this.def59 = newDef59;
	} 	  
	/**
	 * ����def60��Getter����.���������Զ�����60
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef60 () {
		return def60;
	}   
	/**
	 * ����def60��Setter����.���������Զ�����60
	 * ��������:
	 * @param newDef60 java.lang.String
	 */
	public void setDef60 (java.lang.String newDef60 ) {
	 	this.def60 = newDef60;
	} 	  
	/**
	 * ����def61��Getter����.���������Զ�����61
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef61 () {
		return def61;
	}   
	/**
	 * ����def61��Setter����.���������Զ�����61
	 * ��������:
	 * @param newDef61 java.lang.String
	 */
	public void setDef61 (java.lang.String newDef61 ) {
	 	this.def61 = newDef61;
	} 	  
	/**
	 * ����def62��Getter����.���������Զ�����62
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef62 () {
		return def62;
	}   
	/**
	 * ����def62��Setter����.���������Զ�����62
	 * ��������:
	 * @param newDef62 java.lang.String
	 */
	public void setDef62 (java.lang.String newDef62 ) {
	 	this.def62 = newDef62;
	} 	  
	/**
	 * ����def63��Getter����.���������Զ�����63
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef63 () {
		return def63;
	}   
	/**
	 * ����def63��Setter����.���������Զ�����63
	 * ��������:
	 * @param newDef63 java.lang.String
	 */
	public void setDef63 (java.lang.String newDef63 ) {
	 	this.def63 = newDef63;
	} 	  
	/**
	 * ����def64��Getter����.���������Զ�����64
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef64 () {
		return def64;
	}   
	/**
	 * ����def64��Setter����.���������Զ�����64
	 * ��������:
	 * @param newDef64 java.lang.String
	 */
	public void setDef64 (java.lang.String newDef64 ) {
	 	this.def64 = newDef64;
	} 	  
	/**
	 * ����def65��Getter����.���������Զ�����65
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef65 () {
		return def65;
	}   
	/**
	 * ����def65��Setter����.���������Զ�����65
	 * ��������:
	 * @param newDef65 java.lang.String
	 */
	public void setDef65 (java.lang.String newDef65 ) {
	 	this.def65 = newDef65;
	} 	  
	/**
	 * ����def66��Getter����.���������Զ�����66
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef66 () {
		return def66;
	}   
	/**
	 * ����def66��Setter����.���������Զ�����66
	 * ��������:
	 * @param newDef66 java.lang.String
	 */
	public void setDef66 (java.lang.String newDef66 ) {
	 	this.def66 = newDef66;
	} 	  
	/**
	 * ����def67��Getter����.���������Զ�����67
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef67 () {
		return def67;
	}   
	/**
	 * ����def67��Setter����.���������Զ�����67
	 * ��������:
	 * @param newDef67 java.lang.String
	 */
	public void setDef67 (java.lang.String newDef67 ) {
	 	this.def67 = newDef67;
	} 	  
	/**
	 * ����def68��Getter����.���������Զ�����68
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef68 () {
		return def68;
	}   
	/**
	 * ����def68��Setter����.���������Զ�����68
	 * ��������:
	 * @param newDef68 java.lang.String
	 */
	public void setDef68 (java.lang.String newDef68 ) {
	 	this.def68 = newDef68;
	} 	  
	/**
	 * ����def69��Getter����.���������Զ�����69
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef69 () {
		return def69;
	}   
	/**
	 * ����def69��Setter����.���������Զ�����69
	 * ��������:
	 * @param newDef69 java.lang.String
	 */
	public void setDef69 (java.lang.String newDef69 ) {
	 	this.def69 = newDef69;
	} 	  
	/**
	 * ����def70��Getter����.���������Զ�����70
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef70 () {
		return def70;
	}   
	/**
	 * ����def70��Setter����.���������Զ�����70
	 * ��������:
	 * @param newDef70 java.lang.String
	 */
	public void setDef70 (java.lang.String newDef70 ) {
	 	this.def70 = newDef70;
	} 	  
	/**
	 * ����def71��Getter����.���������Զ�����71
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef71 () {
		return def71;
	}   
	/**
	 * ����def71��Setter����.���������Զ�����71
	 * ��������:
	 * @param newDef71 java.lang.String
	 */
	public void setDef71 (java.lang.String newDef71 ) {
	 	this.def71 = newDef71;
	} 	  
	/**
	 * ����def72��Getter����.���������Զ�����72
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef72 () {
		return def72;
	}   
	/**
	 * ����def72��Setter����.���������Զ�����72
	 * ��������:
	 * @param newDef72 java.lang.String
	 */
	public void setDef72 (java.lang.String newDef72 ) {
	 	this.def72 = newDef72;
	} 	  
	/**
	 * ����def73��Getter����.���������Զ�����73
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef73 () {
		return def73;
	}   
	/**
	 * ����def73��Setter����.���������Զ�����73
	 * ��������:
	 * @param newDef73 java.lang.String
	 */
	public void setDef73 (java.lang.String newDef73 ) {
	 	this.def73 = newDef73;
	} 	  
	/**
	 * ����def74��Getter����.���������Զ�����74
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef74 () {
		return def74;
	}   
	/**
	 * ����def74��Setter����.���������Զ�����74
	 * ��������:
	 * @param newDef74 java.lang.String
	 */
	public void setDef74 (java.lang.String newDef74 ) {
	 	this.def74 = newDef74;
	} 	  
	/**
	 * ����def75��Getter����.���������Զ�����75
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef75 () {
		return def75;
	}   
	/**
	 * ����def75��Setter����.���������Զ�����75
	 * ��������:
	 * @param newDef75 java.lang.String
	 */
	public void setDef75 (java.lang.String newDef75 ) {
	 	this.def75 = newDef75;
	} 	  
	/**
	 * ����def76��Getter����.���������Զ�����76
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef76 () {
		return def76;
	}   
	/**
	 * ����def76��Setter����.���������Զ�����76
	 * ��������:
	 * @param newDef76 java.lang.String
	 */
	public void setDef76 (java.lang.String newDef76 ) {
	 	this.def76 = newDef76;
	} 	  
	/**
	 * ����def77��Getter����.���������Զ�����77
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef77 () {
		return def77;
	}   
	/**
	 * ����def77��Setter����.���������Զ�����77
	 * ��������:
	 * @param newDef77 java.lang.String
	 */
	public void setDef77 (java.lang.String newDef77 ) {
	 	this.def77 = newDef77;
	} 	  
	/**
	 * ����def78��Getter����.���������Զ�����78
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef78 () {
		return def78;
	}   
	/**
	 * ����def78��Setter����.���������Զ�����78
	 * ��������:
	 * @param newDef78 java.lang.String
	 */
	public void setDef78 (java.lang.String newDef78 ) {
	 	this.def78 = newDef78;
	} 	  
	/**
	 * ����def79��Getter����.���������Զ�����79
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef79 () {
		return def79;
	}   
	/**
	 * ����def79��Setter����.���������Զ�����79
	 * ��������:
	 * @param newDef79 java.lang.String
	 */
	public void setDef79 (java.lang.String newDef79 ) {
	 	this.def79 = newDef79;
	} 	  
	/**
	 * ����def80��Getter����.���������Զ�����80
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef80 () {
		return def80;
	}   
	/**
	 * ����def80��Setter����.���������Զ�����80
	 * ��������:
	 * @param newDef80 java.lang.String
	 */
	public void setDef80 (java.lang.String newDef80 ) {
	 	this.def80 = newDef80;
	} 	  
	/**
	 * ����def81��Getter����.���������Զ�����81
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef81 () {
		return def81;
	}   
	/**
	 * ����def81��Setter����.���������Զ�����81
	 * ��������:
	 * @param newDef81 java.lang.String
	 */
	public void setDef81 (java.lang.String newDef81 ) {
	 	this.def81 = newDef81;
	} 	  
	/**
	 * ����def82��Getter����.���������Զ�����82
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef82 () {
		return def82;
	}   
	/**
	 * ����def82��Setter����.���������Զ�����82
	 * ��������:
	 * @param newDef82 java.lang.String
	 */
	public void setDef82 (java.lang.String newDef82 ) {
	 	this.def82 = newDef82;
	} 	  
	/**
	 * ����def83��Getter����.���������Զ�����83
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef83 () {
		return def83;
	}   
	/**
	 * ����def83��Setter����.���������Զ�����83
	 * ��������:
	 * @param newDef83 java.lang.String
	 */
	public void setDef83 (java.lang.String newDef83 ) {
	 	this.def83 = newDef83;
	} 	  
	/**
	 * ����def84��Getter����.���������Զ�����84
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef84 () {
		return def84;
	}   
	/**
	 * ����def84��Setter����.���������Զ�����84
	 * ��������:
	 * @param newDef84 java.lang.String
	 */
	public void setDef84 (java.lang.String newDef84 ) {
	 	this.def84 = newDef84;
	} 	  
	/**
	 * ����def85��Getter����.���������Զ�����85
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef85 () {
		return def85;
	}   
	/**
	 * ����def85��Setter����.���������Զ�����85
	 * ��������:
	 * @param newDef85 java.lang.String
	 */
	public void setDef85 (java.lang.String newDef85 ) {
	 	this.def85 = newDef85;
	} 	  
	/**
	 * ����def86��Getter����.���������Զ�����86
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef86 () {
		return def86;
	}   
	/**
	 * ����def86��Setter����.���������Զ�����86
	 * ��������:
	 * @param newDef86 java.lang.String
	 */
	public void setDef86 (java.lang.String newDef86 ) {
	 	this.def86 = newDef86;
	} 	  
	/**
	 * ����def87��Getter����.���������Զ�����87
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef87 () {
		return def87;
	}   
	/**
	 * ����def87��Setter����.���������Զ�����87
	 * ��������:
	 * @param newDef87 java.lang.String
	 */
	public void setDef87 (java.lang.String newDef87 ) {
	 	this.def87 = newDef87;
	} 	  
	/**
	 * ����def88��Getter����.���������Զ�����88
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef88 () {
		return def88;
	}   
	/**
	 * ����def88��Setter����.���������Զ�����88
	 * ��������:
	 * @param newDef88 java.lang.String
	 */
	public void setDef88 (java.lang.String newDef88 ) {
	 	this.def88 = newDef88;
	} 	  
	/**
	 * ����def89��Getter����.���������Զ�����89
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef89 () {
		return def89;
	}   
	/**
	 * ����def89��Setter����.���������Զ�����89
	 * ��������:
	 * @param newDef89 java.lang.String
	 */
	public void setDef89 (java.lang.String newDef89 ) {
	 	this.def89 = newDef89;
	} 	  
	/**
	 * ����def90��Getter����.���������Զ�����90
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef90 () {
		return def90;
	}   
	/**
	 * ����def90��Setter����.���������Զ�����90
	 * ��������:
	 * @param newDef90 java.lang.String
	 */
	public void setDef90 (java.lang.String newDef90 ) {
	 	this.def90 = newDef90;
	} 	  
	/**
	 * ����dr��Getter����.��������dr
	 * ��������:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * ����dr��Setter����.��������dr
	 * ��������:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * ����ts��Getter����.��������ts
	 * ��������:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * ����ts��Setter����.��������ts
	 * ��������:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>ȡ�ø�VO�����ֶ�.
	  * <p>
	  * ��������:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>ȡ�ñ�����.
	  * <p>
	  * ��������:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pm_feebalance";
	}
    
	/**
	 * <p>���ر�����.
	 * <p>
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "pm_feebalance_ct";
	}    
	
	/**
	 * <p>���ر�����.
	 * <p>
	 * ��������:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "pm_feebalance_ct";
	}    
    
    /**
	  * ����Ĭ�Ϸ�ʽ����������.
	  *
	  * ��������:
	  */
     public PmFeebalanceHVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.pm.feebalance.PmFeebalanceHVO" )
	public IVOMeta getMetaData() {
		IVOMeta meta = VOMetaFactory.getInstance().getVOMeta(
				"pm" + "." + "pm_feebalance_ct");
		return meta;
  	}
} 


