/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.pm.feebalance;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> �ڴ˴���Ҫ��������Ĺ��� </b>
 * <p>
 *     �ڴ˴���Ӵ����������Ϣ
 * </p>
 * ��������:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PmFeebalanceBVO extends SuperVO {
	private java.lang.String pm_feebalance;
	private java.lang.String pm_feebalance_b;
	private java.lang.String pk_project;
	private java.lang.String material_code;
	private java.lang.String material_v;
	private nc.vo.pub.lang.UFDouble money;
	private nc.vo.pub.lang.UFDouble unitmoney;
	private nc.vo.pub.lang.UFDouble num;
	private java.lang.String pk_cbsnode;
	private java.lang.String pk_measdoc;
	private nc.vo.pub.lang.UFDouble protocontractmoney;
	private nc.vo.pub.lang.UFDouble paymoney;
	private nc.vo.pub.lang.UFDouble examinationvalue;
	private nc.vo.pub.lang.UFDouble addpaymoney;
	private java.lang.String clearingstate;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.String def11;
	private java.lang.String def12;
	private java.lang.String def13;
	private java.lang.String def14;
	private java.lang.String def15;
	private java.lang.String def16;
	private java.lang.String def17;
	private java.lang.String def18;
	private java.lang.String def19;
	private java.lang.String def20;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_org_v;
	private java.lang.String rowno;
	private java.lang.String tsourcebodyts;
	private java.lang.String tsourceheadts;
	private java.lang.String csourcebillbid;
	private nc.vo.pub.lang.UFDate csourcebilldate;
	private java.lang.String csourcebillhid;
	private java.lang.String csourcetype;
	private java.lang.String cfirstbillbid;
	private nc.vo.pub.lang.UFDate cfirstbilldate;
	private java.lang.String cfirstbillhid;
	private java.lang.String cfirsttranstype;
	private java.lang.String cfirsttype;
	private nc.vo.pub.lang.UFDouble contractalter_mny;
	private nc.vo.pub.lang.UFDouble contractbalance_mny;
	private nc.vo.pub.lang.UFDouble speed_mny;
	private nc.vo.pub.lang.UFDouble settlement_mny;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PM_FEEBALANCE = "pm_feebalance";
	public static final String PM_FEEBALANCE_B = "pm_feebalance_b";
	public static final String PK_PROJECT = "pk_project";
	public static final String MATERIAL_CODE = "material_code";
	public static final String MATERIAL_V = "material_v";
	public static final String MONEY = "money";
	public static final String UNITMONEY = "unitmoney";
	public static final String NUM = "num";
	public static final String PK_CBSNODE = "pk_cbsnode";
	public static final String PK_MEASDOC = "pk_measdoc";
	public static final String PROTOCONTRACTMONEY = "protocontractmoney";
	public static final String PAYMONEY = "paymoney";
	public static final String EXAMINATIONVALUE = "examinationvalue";
	public static final String ADDPAYMONEY = "addpaymoney";
	public static final String CLEARINGSTATE = "clearingstate";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
	public static final String DEF16 = "def16";
	public static final String DEF17 = "def17";
	public static final String DEF18 = "def18";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String ROWNO = "rowno";
	public static final String TSOURCEBODYTS = "tsourcebodyts";
	public static final String TSOURCEHEADTS = "tsourceheadts";
	public static final String CSOURCEBILLBID = "csourcebillbid";
	public static final String CSOURCEBILLDATE = "csourcebilldate";
	public static final String CSOURCEBILLHID = "csourcebillhid";
	public static final String CSOURCETYPE = "csourcetype";
	public static final String CFIRSTBILLBID = "cfirstbillbid";
	public static final String CFIRSTBILLDATE = "cfirstbilldate";
	public static final String CFIRSTBILLHID = "cfirstbillhid";
	public static final String CFIRSTTRANSTYPE = "cfirsttranstype";
	public static final String CFIRSTTYPE = "cfirsttype";
	public static final String CONTRACTALTER_MNY = "contractalter_mny";
	public static final String CONTRACTBALANCE_MNY = "contractbalance_mny";
	public static final String SPEED_MNY = "speed_mny";
	public static final String SETTLEMENT_MNY = "settlement_mny";
			
	/**
	 * ����pm_feebalance��Getter����.��������parentPK
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPm_feebalance () {
		return pm_feebalance;
	}   
	/**
	 * ����pm_feebalance��Setter����.��������parentPK
	 * ��������:
	 * @param newPm_feebalance java.lang.String
	 */
	public void setPm_feebalance (java.lang.String newPm_feebalance ) {
	 	this.pm_feebalance = newPm_feebalance;
	} 	  
	/**
	 * ����pm_feebalance_b��Getter����.���������ӱ�����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPm_feebalance_b () {
		return pm_feebalance_b;
	}   
	/**
	 * ����pm_feebalance_b��Setter����.���������ӱ�����
	 * ��������:
	 * @param newPm_feebalance_b java.lang.String
	 */
	public void setPm_feebalance_b (java.lang.String newPm_feebalance_b ) {
	 	this.pm_feebalance_b = newPm_feebalance_b;
	} 	  
	/**
	 * ����pk_project��Getter����.����������Ŀ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_project () {
		return pk_project;
	}   
	/**
	 * ����pk_project��Setter����.����������Ŀ����
	 * ��������:
	 * @param newPk_project java.lang.String
	 */
	public void setPk_project (java.lang.String newPk_project ) {
	 	this.pk_project = newPk_project;
	} 	  
	/**
	 * ����material_code��Getter����.�����������ϱ���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getMaterial_code () {
		return material_code;
	}   
	/**
	 * ����material_code��Setter����.�����������ϱ���
	 * ��������:
	 * @param newMaterial_code java.lang.String
	 */
	public void setMaterial_code (java.lang.String newMaterial_code ) {
	 	this.material_code = newMaterial_code;
	} 	  
	/**
	 * ����material_v��Getter����.����������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getMaterial_v () {
		return material_v;
	}   
	/**
	 * ����material_v��Setter����.����������������
	 * ��������:
	 * @param newMaterial_v java.lang.String
	 */
	public void setMaterial_v (java.lang.String newMaterial_v ) {
	 	this.material_v = newMaterial_v;
	} 	  
	/**
	 * ����money��Getter����.�����������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getMoney () {
		return money;
	}   
	/**
	 * ����money��Setter����.�����������
	 * ��������:
	 * @param newMoney nc.vo.pub.lang.UFDouble
	 */
	public void setMoney (nc.vo.pub.lang.UFDouble newMoney ) {
	 	this.money = newMoney;
	} 	  
	/**
	 * ����unitmoney��Getter����.������������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getUnitmoney () {
		return unitmoney;
	}   
	/**
	 * ����unitmoney��Setter����.������������
	 * ��������:
	 * @param newUnitmoney nc.vo.pub.lang.UFDouble
	 */
	public void setUnitmoney (nc.vo.pub.lang.UFDouble newUnitmoney ) {
	 	this.unitmoney = newUnitmoney;
	} 	  
	/**
	 * ����num��Getter����.������������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNum () {
		return num;
	}   
	/**
	 * ����num��Setter����.������������
	 * ��������:
	 * @param newNum nc.vo.pub.lang.UFDouble
	 */
	public void setNum (nc.vo.pub.lang.UFDouble newNum ) {
	 	this.num = newNum;
	} 	  
	/**
	 * ����pk_cbsnode��Getter����.��������CBS
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_cbsnode () {
		return pk_cbsnode;
	}   
	/**
	 * ����pk_cbsnode��Setter����.��������CBS
	 * ��������:
	 * @param newPk_cbsnode java.lang.String
	 */
	public void setPk_cbsnode (java.lang.String newPk_cbsnode ) {
	 	this.pk_cbsnode = newPk_cbsnode;
	} 	  
	/**
	 * ����pk_measdoc��Getter����.����������λ
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_measdoc () {
		return pk_measdoc;
	}   
	/**
	 * ����pk_measdoc��Setter����.����������λ
	 * ��������:
	 * @param newPk_measdoc java.lang.String
	 */
	public void setPk_measdoc (java.lang.String newPk_measdoc ) {
	 	this.pk_measdoc = newPk_measdoc;
	} 	  
	/**
	 * ����protocontractmoney��Getter����.��������ԭ��ͬ���
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getProtocontractmoney () {
		return protocontractmoney;
	}   
	/**
	 * ����protocontractmoney��Setter����.��������ԭ��ͬ���
	 * ��������:
	 * @param newProtocontractmoney nc.vo.pub.lang.UFDouble
	 */
	public void setProtocontractmoney (nc.vo.pub.lang.UFDouble newProtocontractmoney ) {
	 	this.protocontractmoney = newProtocontractmoney;
	} 	  
	/**
	 * ����paymoney��Getter����.���������Ѹ�����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getPaymoney () {
		return paymoney;
	}   
	/**
	 * ����paymoney��Setter����.���������Ѹ�����
	 * ��������:
	 * @param newPaymoney nc.vo.pub.lang.UFDouble
	 */
	public void setPaymoney (nc.vo.pub.lang.UFDouble newPaymoney ) {
	 	this.paymoney = newPaymoney;
	} 	  
	/**
	 * ����examinationvalue��Getter����.����������ֵ
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getExaminationvalue () {
		return examinationvalue;
	}   
	/**
	 * ����examinationvalue��Setter����.����������ֵ
	 * ��������:
	 * @param newExaminationvalue nc.vo.pub.lang.UFDouble
	 */
	public void setExaminationvalue (nc.vo.pub.lang.UFDouble newExaminationvalue ) {
	 	this.examinationvalue = newExaminationvalue;
	} 	  
	/**
	 * ����addpaymoney��Getter����.���������ۼƸ�����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getAddpaymoney () {
		return addpaymoney;
	}   
	/**
	 * ����addpaymoney��Setter����.���������ۼƸ�����
	 * ��������:
	 * @param newAddpaymoney nc.vo.pub.lang.UFDouble
	 */
	public void setAddpaymoney (nc.vo.pub.lang.UFDouble newAddpaymoney ) {
	 	this.addpaymoney = newAddpaymoney;
	} 	  
	/**
	 * ����clearingstate��Getter����.������������״̬
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getClearingstate () {
		return clearingstate;
	}   
	/**
	 * ����clearingstate��Setter����.������������״̬
	 * ��������:
	 * @param newClearingstate java.lang.String
	 */
	public void setClearingstate (java.lang.String newClearingstate ) {
	 	this.clearingstate = newClearingstate;
	} 	  
	/**
	 * ����def1��Getter����.���������Զ�����1
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return def1;
	}   
	/**
	 * ����def1��Setter����.���������Զ�����1
	 * ��������:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * ����def2��Getter����.���������Զ�����2
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return def2;
	}   
	/**
	 * ����def2��Setter����.���������Զ�����2
	 * ��������:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * ����def3��Getter����.���������Զ�����3
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return def3;
	}   
	/**
	 * ����def3��Setter����.���������Զ�����3
	 * ��������:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * ����def4��Getter����.���������Զ�����4
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return def4;
	}   
	/**
	 * ����def4��Setter����.���������Զ�����4
	 * ��������:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * ����def5��Getter����.���������Զ�����5
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return def5;
	}   
	/**
	 * ����def5��Setter����.���������Զ�����5
	 * ��������:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * ����def6��Getter����.���������Զ�����6
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return def6;
	}   
	/**
	 * ����def6��Setter����.���������Զ�����6
	 * ��������:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * ����def7��Getter����.���������Զ�����7
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return def7;
	}   
	/**
	 * ����def7��Setter����.���������Զ�����7
	 * ��������:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * ����def8��Getter����.���������Զ�����8
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return def8;
	}   
	/**
	 * ����def8��Setter����.���������Զ�����8
	 * ��������:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * ����def9��Getter����.���������Զ�����9
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return def9;
	}   
	/**
	 * ����def9��Setter����.���������Զ�����9
	 * ��������:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * ����def10��Getter����.���������Զ�����10
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return def10;
	}   
	/**
	 * ����def10��Setter����.���������Զ�����10
	 * ��������:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	this.def10 = newDef10;
	} 	  
	/**
	 * ����def11��Getter����.���������Զ�����11
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef11 () {
		return def11;
	}   
	/**
	 * ����def11��Setter����.���������Զ�����11
	 * ��������:
	 * @param newDef11 java.lang.String
	 */
	public void setDef11 (java.lang.String newDef11 ) {
	 	this.def11 = newDef11;
	} 	  
	/**
	 * ����def12��Getter����.���������Զ�����12
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef12 () {
		return def12;
	}   
	/**
	 * ����def12��Setter����.���������Զ�����12
	 * ��������:
	 * @param newDef12 java.lang.String
	 */
	public void setDef12 (java.lang.String newDef12 ) {
	 	this.def12 = newDef12;
	} 	  
	/**
	 * ����def13��Getter����.���������Զ�����13
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef13 () {
		return def13;
	}   
	/**
	 * ����def13��Setter����.���������Զ�����13
	 * ��������:
	 * @param newDef13 java.lang.String
	 */
	public void setDef13 (java.lang.String newDef13 ) {
	 	this.def13 = newDef13;
	} 	  
	/**
	 * ����def14��Getter����.���������Զ�����14
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef14 () {
		return def14;
	}   
	/**
	 * ����def14��Setter����.���������Զ�����14
	 * ��������:
	 * @param newDef14 java.lang.String
	 */
	public void setDef14 (java.lang.String newDef14 ) {
	 	this.def14 = newDef14;
	} 	  
	/**
	 * ����def15��Getter����.���������Զ�����15
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef15 () {
		return def15;
	}   
	/**
	 * ����def15��Setter����.���������Զ�����15
	 * ��������:
	 * @param newDef15 java.lang.String
	 */
	public void setDef15 (java.lang.String newDef15 ) {
	 	this.def15 = newDef15;
	} 	  
	/**
	 * ����def16��Getter����.���������Զ�����16
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef16 () {
		return def16;
	}   
	/**
	 * ����def16��Setter����.���������Զ�����16
	 * ��������:
	 * @param newDef16 java.lang.String
	 */
	public void setDef16 (java.lang.String newDef16 ) {
	 	this.def16 = newDef16;
	} 	  
	/**
	 * ����def17��Getter����.���������Զ�����17
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef17 () {
		return def17;
	}   
	/**
	 * ����def17��Setter����.���������Զ�����17
	 * ��������:
	 * @param newDef17 java.lang.String
	 */
	public void setDef17 (java.lang.String newDef17 ) {
	 	this.def17 = newDef17;
	} 	  
	/**
	 * ����def18��Getter����.���������Զ�����18
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef18 () {
		return def18;
	}   
	/**
	 * ����def18��Setter����.���������Զ�����18
	 * ��������:
	 * @param newDef18 java.lang.String
	 */
	public void setDef18 (java.lang.String newDef18 ) {
	 	this.def18 = newDef18;
	} 	  
	/**
	 * ����def19��Getter����.���������Զ�����19
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef19 () {
		return def19;
	}   
	/**
	 * ����def19��Setter����.���������Զ�����19
	 * ��������:
	 * @param newDef19 java.lang.String
	 */
	public void setDef19 (java.lang.String newDef19 ) {
	 	this.def19 = newDef19;
	} 	  
	/**
	 * ����def20��Getter����.���������Զ�����20
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getDef20 () {
		return def20;
	}   
	/**
	 * ����def20��Setter����.���������Զ�����20
	 * ��������:
	 * @param newDef20 java.lang.String
	 */
	public void setDef20 (java.lang.String newDef20 ) {
	 	this.def20 = newDef20;
	} 	  
	/**
	 * ����pk_group��Getter����.������������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * ����pk_group��Setter����.������������
	 * ��������:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * ����pk_org��Getter����.����������Ŀ��֯
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * ����pk_org��Setter����.����������Ŀ��֯
	 * ��������:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * ����pk_org_v��Getter����.����������Ŀ��֯���°汾
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v () {
		return pk_org_v;
	}   
	/**
	 * ����pk_org_v��Setter����.����������Ŀ��֯���°汾
	 * ��������:
	 * @param newPk_org_v java.lang.String
	 */
	public void setPk_org_v (java.lang.String newPk_org_v ) {
	 	this.pk_org_v = newPk_org_v;
	} 	  
	/**
	 * ����rowno��Getter����.���������к�
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getRowno () {
		return rowno;
	}   
	/**
	 * ����rowno��Setter����.���������к�
	 * ��������:
	 * @param newRowno java.lang.String
	 */
	public void setRowno (java.lang.String newRowno ) {
	 	this.rowno = newRowno;
	} 	  
	/**
	 * ����tsourcebodyts��Getter����.����������Դ����ʱ���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getTsourcebodyts () {
		return tsourcebodyts;
	}   
	/**
	 * ����tsourcebodyts��Setter����.����������Դ����ʱ���
	 * ��������:
	 * @param newTsourcebodyts java.lang.String
	 */
	public void setTsourcebodyts (java.lang.String newTsourcebodyts ) {
	 	this.tsourcebodyts = newTsourcebodyts;
	} 	  
	/**
	 * ����tsourceheadts��Getter����.����������Դ��ͷʱ���
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getTsourceheadts () {
		return tsourceheadts;
	}   
	/**
	 * ����tsourceheadts��Setter����.����������Դ��ͷʱ���
	 * ��������:
	 * @param newTsourceheadts java.lang.String
	 */
	public void setTsourceheadts (java.lang.String newTsourceheadts ) {
	 	this.tsourceheadts = newTsourceheadts;
	} 	  
	/**
	 * ����csourcebillbid��Getter����.����������Դ���ݱ�������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCsourcebillbid () {
		return csourcebillbid;
	}   
	/**
	 * ����csourcebillbid��Setter����.����������Դ���ݱ�������
	 * ��������:
	 * @param newCsourcebillbid java.lang.String
	 */
	public void setCsourcebillbid (java.lang.String newCsourcebillbid ) {
	 	this.csourcebillbid = newCsourcebillbid;
	} 	  
	/**
	 * ����csourcebilldate��Getter����.����������Դ��������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCsourcebilldate () {
		return csourcebilldate;
	}   
	/**
	 * ����csourcebilldate��Setter����.����������Դ��������
	 * ��������:
	 * @param newCsourcebilldate nc.vo.pub.lang.UFDate
	 */
	public void setCsourcebilldate (nc.vo.pub.lang.UFDate newCsourcebilldate ) {
	 	this.csourcebilldate = newCsourcebilldate;
	} 	  
	/**
	 * ����csourcebillhid��Getter����.����������Դ���ݱ�ͷ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCsourcebillhid () {
		return csourcebillhid;
	}   
	/**
	 * ����csourcebillhid��Setter����.����������Դ���ݱ�ͷ����
	 * ��������:
	 * @param newCsourcebillhid java.lang.String
	 */
	public void setCsourcebillhid (java.lang.String newCsourcebillhid ) {
	 	this.csourcebillhid = newCsourcebillhid;
	} 	  
	/**
	 * ����csourcetype��Getter����.����������Դ��������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCsourcetype () {
		return csourcetype;
	}   
	/**
	 * ����csourcetype��Setter����.����������Դ��������
	 * ��������:
	 * @param newCsourcetype java.lang.String
	 */
	public void setCsourcetype (java.lang.String newCsourcetype ) {
	 	this.csourcetype = newCsourcetype;
	} 	  
	/**
	 * ����cfirstbillbid��Getter����.��������Դͷ���ݱ�������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCfirstbillbid () {
		return cfirstbillbid;
	}   
	/**
	 * ����cfirstbillbid��Setter����.��������Դͷ���ݱ�������
	 * ��������:
	 * @param newCfirstbillbid java.lang.String
	 */
	public void setCfirstbillbid (java.lang.String newCfirstbillbid ) {
	 	this.cfirstbillbid = newCfirstbillbid;
	} 	  
	/**
	 * ����cfirstbilldate��Getter����.��������Դͷ��������
	 * ��������:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getCfirstbilldate () {
		return cfirstbilldate;
	}   
	/**
	 * ����cfirstbilldate��Setter����.��������Դͷ��������
	 * ��������:
	 * @param newCfirstbilldate nc.vo.pub.lang.UFDate
	 */
	public void setCfirstbilldate (nc.vo.pub.lang.UFDate newCfirstbilldate ) {
	 	this.cfirstbilldate = newCfirstbilldate;
	} 	  
	/**
	 * ����cfirstbillhid��Getter����.��������Դͷ���ݱ�ͷ����
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCfirstbillhid () {
		return cfirstbillhid;
	}   
	/**
	 * ����cfirstbillhid��Setter����.��������Դͷ���ݱ�ͷ����
	 * ��������:
	 * @param newCfirstbillhid java.lang.String
	 */
	public void setCfirstbillhid (java.lang.String newCfirstbillhid ) {
	 	this.cfirstbillhid = newCfirstbillhid;
	} 	  
	/**
	 * ����cfirsttranstype��Getter����.��������Դͷ��������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCfirsttranstype () {
		return cfirsttranstype;
	}   
	/**
	 * ����cfirsttranstype��Setter����.��������Դͷ��������
	 * ��������:
	 * @param newCfirsttranstype java.lang.String
	 */
	public void setCfirsttranstype (java.lang.String newCfirsttranstype ) {
	 	this.cfirsttranstype = newCfirsttranstype;
	} 	  
	/**
	 * ����cfirsttype��Getter����.��������Դͷ��������
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getCfirsttype () {
		return cfirsttype;
	}   
	/**
	 * ����cfirsttype��Setter����.��������Դͷ��������
	 * ��������:
	 * @param newCfirsttype java.lang.String
	 */
	public void setCfirsttype (java.lang.String newCfirsttype ) {
	 	this.cfirsttype = newCfirsttype;
	} 	  
	/**
	 * ����contractalter_mny��Getter����.���������ۼƽ���
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getContractalter_mny () {
		return contractalter_mny;
	}   
	/**
	 * ����contractalter_mny��Setter����.���������ۼƽ���
	 * ��������:
	 * @param newContractalter_mny nc.vo.pub.lang.UFDouble
	 */
	public void setContractalter_mny (nc.vo.pub.lang.UFDouble newContractalter_mny ) {
	 	this.contractalter_mny = newContractalter_mny;
	} 	  
	/**
	 * ����contractbalance_mny��Getter����.���������ۼƽ���
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getContractbalance_mny () {
		return contractbalance_mny;
	}   
	/**
	 * ����contractbalance_mny��Setter����.���������ۼƽ���
	 * ��������:
	 * @param newContractbalance_mny nc.vo.pub.lang.UFDouble
	 */
	public void setContractbalance_mny (nc.vo.pub.lang.UFDouble newContractbalance_mny ) {
	 	this.contractbalance_mny = newContractbalance_mny;
	} 	  
	/**
	 * ����speed_mny��Getter����.���������ۼƽ��Ƚ��
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getSpeed_mny () {
		return speed_mny;
	}   
	/**
	 * ����speed_mny��Setter����.���������ۼƽ��Ƚ��
	 * ��������:
	 * @param newSpeed_mny nc.vo.pub.lang.UFDouble
	 */
	public void setSpeed_mny (nc.vo.pub.lang.UFDouble newSpeed_mny ) {
	 	this.speed_mny = newSpeed_mny;
	} 	  
	/**
	 * ����settlement_mny��Getter����.���������ۼƽ�����
	 * ��������:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getSettlement_mny () {
		return settlement_mny;
	}   
	/**
	 * ����settlement_mny��Setter����.���������ۼƽ�����
	 * ��������:
	 * @param newSettlement_mny nc.vo.pub.lang.UFDouble
	 */
	public void setSettlement_mny (nc.vo.pub.lang.UFDouble newSettlement_mny ) {
	 	this.settlement_mny = newSettlement_mny;
	} 	  
	/**
	 * ����dr��Getter����.��������dr
	 * ��������:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * ����dr��Setter����.��������dr
	 * ��������:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * ����ts��Getter����.��������ts
	 * ��������:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * ����ts��Setter����.��������ts
	 * ��������:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>ȡ�ø�VO�����ֶ�.
	  * <p>
	  * ��������:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pm_feebalance";
	}   
    
	/**
	  * <p>ȡ�ñ�����.
	  * <p>
	  * ��������:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pm_feebalance_b";
	}
    
	/**
	 * <p>���ر�����.
	 * <p>
	 * ��������:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "pm_feebalance_ct_b";
	}    
	
	/**
	 * <p>���ر�����.
	 * <p>
	 * ��������:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "pm_feebalance_ct_b";
	}    
    
    /**
	  * ����Ĭ�Ϸ�ʽ����������.
	  *
	  * ��������:
	  */
     public PmFeebalanceBVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.pm.feebalance.PmFeebalanceBVO" )
	public IVOMeta getMetaData() {
		IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("pm" + "." + "pm_feebalance_ct_b");
		return meta;
  	}
} 


