/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ic.m45.entity;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PurchaseInLocationVO extends SuperVO {
	private java.lang.String cgeneralbid;

	public static final String CGENERALBID = "cgeneralbid";
			
	/**
	 * 属性cgeneralbid的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCgeneralbid () {
		return cgeneralbid;
	}   
	/**
	 * 属性cgeneralbid的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newCgeneralbid java.lang.String
	 */
	public void setCgeneralbid (java.lang.String newCgeneralbid ) {
	 	this.cgeneralbid = newCgeneralbid;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "cgeneralbid";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "cgenerallid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "ic_purchasein_l";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "ic_purchasein_l";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public PurchaseInLocationVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.ic.m45.entity.PurchaseInLocationVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


