/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
 \***************************************************************/
package nc.vo.arap.payable;

import nc.itf.arap.fieldmap.IBillFieldGet;
import nc.vo.arap.basebill.BaseItemVO;
import nc.vo.arap.pub.VOMetaFactory;
import nc.vo.pub.IVOMeta;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2009-06-24 10:54:28
 * 
 * @author
 * @version NCPrj ??
 */
public class PayableBillItemVO extends BaseItemVO {
	private static final long serialVersionUID = 1860925983992650059L;

	public static final String TABLE_NAME = "ap_payableitem";

	public static final String PK_ORG = "pk_org";
	public static final String PK_FIORG = "pk_fiorg";
	public static final String PK_PCORG = "pk_pcorg";
	public static final String PK_PCORG_V = "pk_pcorg_v";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String PK_FIORG_V = "pk_fiorg_v";
	public static final String SETT_ORG_V = "sett_org_v";
	public static final String PU_DEPTID = "pu_deptid";
	public static final String PU_PSNDOC = "pu_psndoc";
	public static final String PU_ORG = "pu_org";
	public static final String SETT_ORG = "sett_org";
	public static final String MATERIAL = "material";
	public static final String SUPPLIER = "supplier";
	public static final String POSTUNIT = "postunit";
	public static final String POSTPRICENOTAX = "postpricenotax";
	public static final String POSTQUANTITY = "postquantity";
	public static final String POSTPRICE = "postprice";
	public static final String COORDFLAG = "coordflag";
	public static final String EQUIPMENTCODE = "equipmentcode";
	public static final String PRODUCTLINE = "productline";
	public static final String CASHITEM = "cashitem";
	public static final String BANKROLLPROJET = "bankrollprojet";
	public static final String PAUSETRANSACT = "pausetransact";
	public static final String BILLDATE = "billdate";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String BILLCLASS = "billclass";
	public static final String PK_TRADETYPE = "pk_tradetype";
	public static final String PK_TRADETYPEID = "pk_tradetypeid";
	public static final String PK_PAYABLEBILL = "pk_payablebill";
	public static final String PK_PAYABLEITEM = "pk_payableitem";
	public static final String BUSIDATE = "busidate";
	public static final String PK_SUBJCODE = "pk_subjcode";
	public static final String BILLNO = "billno";
	public static final String OBJTYPE = "objtype";
	public static final String ROWNO = "rowno";
	public static final String ROWTYPE = "rowtype";
	public static final String DIRECTION = "direction";
	public static final String CHECKTYPE = "checktype";
	public static final String PK_SSITEM = "pk_ssitem";
	public static final String SCOMMENT = "scomment";
	public static final String SUBJCODE = "subjcode";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String RATE = "rate";
	public static final String PK_DEPTID = "pk_deptid";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String QUANTITY_CR = "quantity_cr";
	public static final String LOCAL_MONEY_CR = "local_money_cr";
	public static final String MONEY_CR = "money_cr";
	public static final String MONEY_BAL = "money_bal";
	public static final String LOCAL_MONEY_BAL = "local_money_bal";
	public static final String QUANTITY_BAL = "quantity_bal";
	public static final String LOCAL_TAX_CR = "local_tax_cr";
	public static final String NOTAX_CR = "notax_cr";
	public static final String LOCAL_NOTAX_CR = "local_notax_cr";
	public static final String PRICE = "price";
	public static final String TAXPRICE = "taxprice";
	public static final String TAXRATE = "taxrate";
	public static final String TAXNUM = "taxnum";
	public static final String TOP_BILLID = "top_billid";
	public static final String TOP_ITEMID = "top_itemid";
	public static final String TOP_BILLTYPE = "top_billtype";
	public static final String TOP_TRADETYPE = "top_tradetype";
	public static final String SRC_TRADETYPE = "src_tradetype";
	public static final String SRC_BILLTYPE = "src_billtype";
	public static final String SRC_BILLID = "src_billid";
	public static final String SRC_ITEMID = "src_itemid";
	public static final String TAXTYPE = "taxtype";
	public static final String PK_PAYTERM = "pk_payterm";
	public static final String PAYACCOUNT = "payaccount";
	public static final String RECACCOUNT = "recaccount";
	public static final String ORDERCUBASDOC = "ordercubasdoc";
	public static final String INNERORDERNO = "innerorderno";
	public static final String ASSETPACTNO = "assetpactno";
	public static final String CONTRACTNO = "contractno";
	public static final String FREECUST = "freecust";
	public static final String FACARD = "facard";
	public static final String PURCHASEORDER = "purchaseorder";
	public static final String INVOICENO = "invoiceno";
	public static final String OUTSTORENO = "outstoreno";
	public static final String PK_JOBPHASE = "pk_jobphase";
	public static final String PK_JOB = "pk_job";
	public static final String DEF30 = "def30";
	public static final String DEF29 = "def29";
	public static final String DEF28 = "def28";
	public static final String DEF27 = "def27";
	public static final String DEF26 = "def26";
	public static final String DEF25 = "def25";
	public static final String DEF24 = "def24";
	public static final String DEF23 = "def23";
	public static final String DEF22 = "def22";
	public static final String DEF21 = "def21";
	public static final String DEF20 = "def20";
	public static final String DEF19 = "def19";
	public static final String DEF18 = "def18";
	public static final String DEF17 = "def17";
	public static final String DEF16 = "def16";
	public static final String DEF15 = "def15";
	public static final String DEF14 = "def14";
	public static final String DEF13 = "def13";
	public static final String DEF12 = "def12";
	public static final String DEF11 = "def11";
	public static final String DEF10 = "def10";
	public static final String DEF9 = "def9";
	public static final String DEF8 = "def8";
	public static final String DEF7 = "def7";
	public static final String DEF6 = "def6";
	public static final String DEF5 = "def5";
	public static final String DEF4 = "def4";
	public static final String DEF3 = "def3";
	public static final String DEF2 = "def2";
	public static final String DEF1 = "def1";
	public static final String CHECKELEMENT = "checkelement";
	public static final String GROUPRATE = "grouprate";
	public static final String GLOBALRATE = "globalrate";
	public static final String PU_ORG_V = "pu_org_v";
	public static final String GROUPCREBIT = "groupcrebit";
	public static final String GLOBALCREBIT = "globalcrebit";
	public static final String GROUPBALANCE = "groupbalance";
	public static final String GLOBALBALANCE = "globalbalance";
	public static final String GROUPTAX_CRE = "grouptax_cre";
	public static final String GLOBALTAX_CRE = "globaltax_cre";
	public static final String GROUPNOTAX_CRE = "groupnotax_cre";
	public static final String GLOBALNOTAX_CRE = "globalnotax_cre";
	public static final String OCCUPATIONMNY = "occupationmny";
	public static final String PROJECT = "project";
	public static final String PROJECT_TASK = "project_task";
	public static final String SETTLENO = "settleno";
	public static final String TOP_CHANGETS = "top_changets";

	private String pk_payableitem;

	private String pk_payablebill;

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2009-06-24 10:54:28
	 */
	public PayableBillItemVO() {
		super();
		setBillclass(IBillFieldGet.YF);
	}

	public IVOMeta getMetaData() {
		IVOMeta meta = VOMetaFactory.getInstance()
				.getVOMeta("arap.payableitem");
		return meta;
	}

	@Override
	public String getChildrenPK() {
		return pk_payableitem;
	}

	@Override
	public String getParentPK() {
		return pk_payablebill == null ? (String) getAttributeValue(PK_PAYABLEBILL)
				: pk_payablebill;
	}

	@Override
	public void setChildrenPK(String pk_payableitem) {
		this.pk_payableitem = pk_payableitem;
	}

	@Override
	public void setParentPK(String pk_payablebill) {
		this.pk_payablebill = pk_payablebill;

	}

	public String getPk_payableitem() {
		return pk_payableitem;
	}

	public void setPk_payableitem(String pkPayableitem) {
		pk_payableitem = pkPayableitem;
	}

	public String getPk_payablebill() {
		return pk_payablebill;
	}

	public void setPk_payablebill(String pkPayablebill) {
		pk_payablebill = pkPayablebill;
	}

	public static String getDefaultTable() {
		return TABLE_NAME;
	}

	public java.lang.String getParentPKFieldName() {
		return PK_PAYABLEBILL;
	}

	// add by zengzw@ 2016年4月22日16:14:34 begin
	public static final String DEF31 = "def31";
	public static final String DEF32 = "def32";
	public static final String DEF33 = "def33";
	public static final String DEF34 = "def34";
	public static final String DEF35 = "def35";
	public static final String DEF36 = "def36";
	public static final String DEF37 = "def37";
	public static final String DEF38 = "def38";
	public static final String DEF39 = "def39";
	public static final String DEF40 = "def40";

	public static final String DEF41 = "def41";
	public static final String DEF42 = "def42";
	public static final String DEF43 = "def43";
	public static final String DEF44 = "def44";
	public static final String DEF45 = "def45";
	public static final String DEF46 = "def46";
	public static final String DEF47 = "def47";
	public static final String DEF48 = "def48";
	public static final String DEF49 = "def49";
	public static final String DEF50 = "def50";

	public static final String DEF51 = "def51";
	public static final String DEF52 = "def52";
	public static final String DEF53 = "def53";
	public static final String DEF54 = "def54";
	public static final String DEF55 = "def55";
	public static final String DEF56 = "def56";
	public static final String DEF57 = "def57";
	public static final String DEF58 = "def58";
	public static final String DEF59 = "def59";
	public static final String DEF60 = "def60";

	public static final String DEF61 = "def61";
	public static final String DEF62 = "def62";
	public static final String DEF63 = "def63";
	public static final String DEF64 = "def64";
	public static final String DEF65 = "def65";
	public static final String DEF66 = "def66";
	public static final String DEF67 = "def67";
	public static final String DEF68 = "def68";
	public static final String DEF69 = "def69";
	public static final String DEF70 = "def70";

	public static final String DEF71 = "def71";
	public static final String DEF72 = "def72";
	public static final String DEF73 = "def73";
	public static final String DEF74 = "def74";
	public static final String DEF75 = "def75";
	public static final String DEF76 = "def76";
	public static final String DEF77 = "def77";
	public static final String DEF78 = "def78";
	public static final String DEF79 = "def79";
	public static final String DEF80 = "def80";

	// XBX新增100个自定义项
	public static final String DEF81 = "def81";
	public static final String DEF82 = "def82";
	public static final String DEF83 = "def83";
	public static final String DEF84 = "def84";
	public static final String DEF85 = "def85";
	public static final String DEF86 = "def86";
	public static final String DEF87 = "def87";
	public static final String DEF88 = "def88";
	public static final String DEF89 = "def89";
	public static final String DEF90 = "def90";
	public static final String DEF91 = "def91";
	public static final String DEF92 = "def92";
	public static final String DEF93 = "def93";
	public static final String DEF94 = "def94";
	public static final String DEF95 = "def95";
	public static final String DEF96 = "def96";
	public static final String DEF97 = "def97";
	public static final String DEF98 = "def98";
	public static final String DEF99 = "def99";
	public static final String DEF100 = "DEF100";
	public static final String DEF101 = "DEF101";
	public static final String DEF102 = "DEF102";
	public static final String DEF103 = "DEF103";
	public static final String DEF104 = "DEF104";
	public static final String DEF105 = "DEF105";
	public static final String DEF106 = "DEF106";
	public static final String DEF107 = "DEF107";
	public static final String DEF108 = "DEF108";
	public static final String DEF109 = "DEF109";
	public static final String DEF110 = "DEF110";
	public static final String DEF111 = "DEF111";
	public static final String DEF112 = "DEF112";
	public static final String DEF113 = "DEF113";
	public static final String DEF114 = "DEF114";
	public static final String DEF115 = "DEF115";
	public static final String DEF116 = "DEF116";
	public static final String DEF117 = "DEF117";
	public static final String DEF118 = "DEF118";
	public static final String DEF119 = "DEF119";
	public static final String DEF120 = "DEF120";
	public static final String DEF121 = "DEF121";
	public static final String DEF122 = "DEF122";
	public static final String DEF123 = "DEF123";
	public static final String DEF124 = "DEF124";
	public static final String DEF125 = "DEF125";
	public static final String DEF126 = "DEF126";
	public static final String DEF127 = "DEF127";
	public static final String DEF128 = "DEF128";
	public static final String DEF129 = "DEF129";
	public static final String DEF130 = "DEF130";
	public static final String DEF131 = "DEF131";
	public static final String DEF132 = "DEF132";
	public static final String DEF133 = "DEF133";
	public static final String DEF134 = "DEF134";
	public static final String DEF135 = "DEF135";
	public static final String DEF136 = "DEF136";
	public static final String DEF137 = "DEF137";
	public static final String DEF138 = "DEF138";
	public static final String DEF139 = "DEF139";
	public static final String DEF140 = "DEF140";
	public static final String DEF141 = "DEF141";
	public static final String DEF142 = "DEF142";
	public static final String DEF143 = "DEF143";
	public static final String DEF144 = "DEF144";
	public static final String DEF145 = "DEF145";
	public static final String DEF146 = "DEF146";
	public static final String DEF147 = "DEF147";
	public static final String DEF148 = "DEF148";
	public static final String DEF149 = "DEF149";
	public static final String DEF150 = "DEF150";
	public static final String DEF151 = "DEF151";
	public static final String DEF152 = "DEF152";
	public static final String DEF153 = "DEF153";
	public static final String DEF154 = "DEF154";
	public static final String DEF155 = "DEF155";
	public static final String DEF156 = "DEF156";
	public static final String DEF157 = "DEF157";
	public static final String DEF158 = "DEF158";
	public static final String DEF159 = "DEF159";
	public static final String DEF160 = "DEF160";
	public static final String DEF161 = "DEF161";
	public static final String DEF162 = "DEF162";
	public static final String DEF163 = "DEF163";
	public static final String DEF164 = "DEF164";
	public static final String DEF165 = "DEF165";
	public static final String DEF166 = "DEF166";
	public static final String DEF167 = "DEF167";
	public static final String DEF168 = "DEF168";
	public static final String DEF169 = "DEF169";
	public static final String DEF170 = "DEF170";
	public static final String DEF171 = "DEF171";
	public static final String DEF172 = "DEF172";
	public static final String DEF173 = "DEF173";
	public static final String DEF174 = "DEF174";
	public static final String DEF175 = "DEF175";
	public static final String DEF176 = "DEF176";
	public static final String DEF177 = "DEF177";
	public static final String DEF178 = "DEF178";
	public static final String DEF179 = "DEF179";
	public static final String DEF180 = "DEF180";

	private String def31;
	private String def32;
	private String def33;
	private String def34;
	private String def35;
	private String def36;
	private String def37;
	private String def38;
	private String def39;
	private String def40;
	private String def41;
	private String def42;
	private String def43;
	private String def44;
	private String def45;
	private String def46;
	private String def47;
	private String def48;
	private String def49;
	private String def50;
	private String def51;
	private String def52;
	private String def53;
	private String def54;
	private String def55;
	private String def56;
	private String def57;
	private String def58;
	private String def59;
	private String def60;
	private String def61;
	private String def62;
	private String def63;
	private String def64;
	private String def65;
	private String def66;
	private String def67;
	private String def68;
	private String def69;
	private String def70;
	private String def71;
	private String def72;
	private String def73;
	private String def74;
	private String def75;
	private String def76;
	private String def77;
	private String def78;
	private String def79;
	private String def80;
	// XBX新增100个自定义项
	private String def81;
	private String def82;
	private String def83;
	private String def84;
	private String def85;
	private String def86;
	private String def87;
	private String def88;
	private String def89;
	private String def90;
	private String def91;
	private String def92;
	private String def93;
	private String def94;
	private String def95;
	private String def96;
	private String def97;
	private String def98;
	private String def99;
	private String def100;
	private String def101;
	private String def102;
	private String def103;
	private String def104;
	private String def105;
	private String def106;
	private String def107;
	private String def108;
	private String def109;
	private String def110;
	private String def111;
	private String def112;
	private String def113;
	private String def114;
	private String def115;
	private String def116;
	private String def117;
	private String def118;
	private String def119;
	private String def120;
	private String def121;
	private String def122;
	private String def123;
	private String def124;
	private String def125;
	private String def126;
	private String def127;
	private String def128;
	private String def129;
	private String def130;
	private String def131;
	private String def132;
	private String def133;
	private String def134;
	private String def135;
	private String def136;
	private String def137;
	private String def138;
	private String def139;
	private String def140;
	private String def141;
	private String def142;
	private String def143;
	private String def144;
	private String def145;
	private String def146;
	private String def147;
	private String def148;
	private String def149;
	private String def150;
	private String def151;
	private String def152;
	private String def153;
	private String def154;
	private String def155;
	private String def156;
	private String def157;
	private String def158;
	private String def159;
	private String def160;
	private String def161;
	private String def162;
	private String def163;
	private String def164;
	private String def165;
	private String def166;
	private String def167;
	private String def168;
	private String def169;
	private String def170;
	private String def171;
	private String def172;
	private String def173;
	private String def174;
	private String def175;
	private String def176;
	private String def177;
	private String def178;
	private String def179;
	private String def180;

	public String getDef31() {
		return def31;
	}

	public void setDef31(String def31) {
		this.def31 = def31;
	}

	public String getDef32() {
		return def32;
	}

	public void setDef32(String def32) {
		this.def32 = def32;
	}

	public String getDef33() {
		return def33;
	}

	public void setDef33(String def33) {
		this.def33 = def33;
	}

	public String getDef34() {
		return def34;
	}

	public void setDef34(String def34) {
		this.def34 = def34;
	}

	public String getDef35() {
		return def35;
	}

	public void setDef35(String def35) {
		this.def35 = def35;
	}

	public String getDef36() {
		return def36;
	}

	public void setDef36(String def36) {
		this.def36 = def36;
	}

	public String getDef37() {
		return def37;
	}

	public void setDef37(String def37) {
		this.def37 = def37;
	}

	public String getDef38() {
		return def38;
	}

	public void setDef38(String def38) {
		this.def38 = def38;
	}

	public String getDef39() {
		return def39;
	}

	public void setDef39(String def39) {
		this.def39 = def39;
	}

	public String getDef40() {
		return def40;
	}

	public void setDef40(String def40) {
		this.def40 = def40;
	}

	public String getDef41() {
		return def41;
	}

	public void setDef41(String def41) {
		this.def41 = def41;
	}

	public String getDef42() {
		return def42;
	}

	public void setDef42(String def42) {
		this.def42 = def42;
	}

	public String getDef43() {
		return def43;
	}

	public void setDef43(String def43) {
		this.def43 = def43;
	}

	public String getDef44() {
		return def44;
	}

	public void setDef44(String def44) {
		this.def44 = def44;
	}

	public String getDef45() {
		return def45;
	}

	public void setDef45(String def45) {
		this.def45 = def45;
	}

	public String getDef46() {
		return def46;
	}

	public void setDef46(String def46) {
		this.def46 = def46;
	}

	public String getDef47() {
		return def47;
	}

	public void setDef47(String def47) {
		this.def47 = def47;
	}

	public String getDef48() {
		return def48;
	}

	public void setDef48(String def48) {
		this.def48 = def48;
	}

	public String getDef49() {
		return def49;
	}

	public void setDef49(String def49) {
		this.def49 = def49;
	}

	public String getDef50() {
		return def50;
	}

	public void setDef50(String def50) {
		this.def50 = def50;
	}

	public String getDef51() {
		return def51;
	}

	public void setDef51(String def51) {
		this.def51 = def51;
	}

	public String getDef52() {
		return def52;
	}

	public void setDef52(String def52) {
		this.def52 = def52;
	}

	public String getDef53() {
		return def53;
	}

	public void setDef53(String def53) {
		this.def53 = def53;
	}

	public String getDef54() {
		return def54;
	}

	public void setDef54(String def54) {
		this.def54 = def54;
	}

	public String getDef55() {
		return def55;
	}

	public void setDef55(String def55) {
		this.def55 = def55;
	}

	public String getDef56() {
		return def56;
	}

	public void setDef56(String def56) {
		this.def56 = def56;
	}

	public String getDef57() {
		return def57;
	}

	public void setDef57(String def57) {
		this.def57 = def57;
	}

	public String getDef58() {
		return def58;
	}

	public void setDef58(String def58) {
		this.def58 = def58;
	}

	public String getDef59() {
		return def59;
	}

	public void setDef59(String def59) {
		this.def59 = def59;
	}

	public String getDef60() {
		return def60;
	}

	public void setDef60(String def60) {
		this.def60 = def60;
	}

	public String getDef61() {
		return def61;
	}

	public void setDef61(String def61) {
		this.def61 = def61;
	}

	public String getDef62() {
		return def62;
	}

	public void setDef62(String def62) {
		this.def62 = def62;
	}

	public String getDef63() {
		return def63;
	}

	public void setDef63(String def63) {
		this.def63 = def63;
	}

	public String getDef64() {
		return def64;
	}

	public void setDef64(String def64) {
		this.def64 = def64;
	}

	public String getDef65() {
		return def65;
	}

	public void setDef65(String def65) {
		this.def65 = def65;
	}

	public String getDef66() {
		return def66;
	}

	public void setDef66(String def66) {
		this.def66 = def66;
	}

	public String getDef67() {
		return def67;
	}

	public void setDef67(String def67) {
		this.def67 = def67;
	}

	public String getDef68() {
		return def68;
	}

	public void setDef68(String def68) {
		this.def68 = def68;
	}

	public String getDef69() {
		return def69;
	}

	public void setDef69(String def69) {
		this.def69 = def69;
	}

	public String getDef70() {
		return def70;
	}

	public void setDef70(String def70) {
		this.def70 = def70;
	}

	public String getDef71() {
		return def71;
	}

	public void setDef71(String def71) {
		this.def71 = def71;
	}

	public String getDef72() {
		return def72;
	}

	public void setDef72(String def72) {
		this.def72 = def72;
	}

	public String getDef73() {
		return def73;
	}

	public void setDef73(String def73) {
		this.def73 = def73;
	}

	public String getDef74() {
		return def74;
	}

	public void setDef74(String def74) {
		this.def74 = def74;
	}

	public String getDef75() {
		return def75;
	}

	public void setDef75(String def75) {
		this.def75 = def75;
	}

	public String getDef76() {
		return def76;
	}

	public void setDef76(String def76) {
		this.def76 = def76;
	}

	public String getDef77() {
		return def77;
	}

	public void setDef77(String def77) {
		this.def77 = def77;
	}

	public String getDef78() {
		return def78;
	}

	public void setDef78(String def78) {
		this.def78 = def78;
	}

	public String getDef79() {
		return def79;
	}

	public void setDef79(String def79) {
		this.def79 = def79;
	}

	public String getDef80() {
		return def80;
	}

	public void setDef80(String def80) {
		this.def80 = def80;
	}

	// XBX新增自定义项100个
	public String getDef81() {
		return this.def81;
	}

	public void setDef81(String def81) {
		this.def81 = def81;
	}

	public String getDef82() {
		return this.def82;
	}

	public void setDef82(String def82) {
		this.def82 = def82;
	}

	public String getDef83() {
		return this.def83;
	}

	public void setDef83(String def83) {
		this.def83 = def83;
	}

	public String getDef84() {
		return this.def84;
	}

	public void setDef84(String def84) {
		this.def84 = def84;
	}

	public String getDef85() {
		return this.def85;
	}

	public void setDef85(String def85) {
		this.def85 = def85;
	}

	public String getDef86() {
		return this.def86;
	}

	public void setDef86(String def86) {
		this.def86 = def86;
	}

	public String getDef87() {
		return this.def87;
	}

	public void setDef87(String def87) {
		this.def87 = def87;
	}

	public String getDef88() {
		return this.def88;
	}

	public void setDef88(String def88) {
		this.def88 = def88;
	}

	public String getDef89() {
		return this.def89;
	}

	public void setDef89(String def89) {
		this.def89 = def89;
	}

	public String getDef90() {
		return this.def90;
	}

	public void setDef90(String def90) {
		this.def90 = def90;
	}

	public String getDef91() {
		return this.def91;
	}

	public void setDef91(String def91) {
		this.def91 = def91;
	}

	public String getDef92() {
		return this.def92;
	}

	public void setDef92(String def92) {
		this.def92 = def92;
	}

	public String getDef93() {
		return this.def93;
	}

	public void setDef93(String def93) {
		this.def93 = def93;
	}

	public String getDef94() {
		return this.def94;
	}

	public void setDef94(String def94) {
		this.def94 = def94;
	}

	public String getDef95() {
		return this.def95;
	}

	public void setDef95(String def95) {
		this.def95 = def95;
	}

	public String getDef96() {
		return this.def96;
	}

	public void setDef96(String def96) {
		this.def96 = def96;
	}

	public String getDef97() {
		return this.def97;
	}

	public void setDef97(String def97) {
		this.def97 = def97;
	}

	public String getDef98() {
		return this.def98;
	}

	public void setDef98(String def98) {
		this.def98 = def98;
	}

	public String getDef99() {
		return this.def99;
	}

	public void setDef99(String def99) {
		this.def99 = def99;
	}

	public String getDef100() {
		return this.def100;
	}

	public void setDef100(String def100) {
		this.def100 = def100;
	}

	public String getDef101() {
		return this.def101;
	}

	public void setDef101(String def101) {
		this.def101 = def101;
	}

	public String getDef102() {
		return this.def102;
	}

	public void setDef102(String def102) {
		this.def102 = def102;
	}

	public String getDef103() {
		return this.def103;
	}

	public void setDef103(String def103) {
		this.def103 = def103;
	}

	public String getDef104() {
		return this.def104;
	}

	public void setDef104(String def104) {
		this.def104 = def104;
	}

	public String getDef105() {
		return this.def105;
	}

	public void setDef105(String def105) {
		this.def105 = def105;
	}

	public String getDef106() {
		return this.def106;
	}

	public void setDef106(String def106) {
		this.def106 = def106;
	}

	public String getDef107() {
		return this.def107;
	}

	public void setDef107(String def107) {
		this.def107 = def107;
	}

	public String getDef108() {
		return this.def108;
	}

	public void setDef108(String def108) {
		this.def108 = def108;
	}

	public String getDef109() {
		return this.def109;
	}

	public void setDef109(String def109) {
		this.def109 = def109;
	}

	public String getDef110() {
		return this.def110;
	}

	public void setDef110(String def110) {
		this.def110 = def110;
	}

	public String getDef111() {
		return this.def111;
	}

	public void setDef111(String def111) {
		this.def111 = def111;
	}

	public String getDef112() {
		return this.def112;
	}

	public void setDef112(String def112) {
		this.def112 = def112;
	}

	public String getDef113() {
		return this.def113;
	}

	public void setDef113(String def113) {
		this.def113 = def113;
	}

	public String getDef114() {
		return this.def114;
	}

	public void setDef114(String def114) {
		this.def114 = def114;
	}

	public String getDef115() {
		return this.def115;
	}

	public void setDef115(String def115) {
		this.def115 = def115;
	}

	public String getDef116() {
		return this.def116;
	}

	public void setDef116(String def116) {
		this.def116 = def116;
	}

	public String getDef117() {
		return this.def117;
	}

	public void setDef117(String def117) {
		this.def117 = def117;
	}

	public String getDef118() {
		return this.def118;
	}

	public void setDef118(String def118) {
		this.def118 = def118;
	}

	public String getDef119() {
		return this.def119;
	}

	public void setDef119(String def119) {
		this.def119 = def119;
	}

	public String getDef120() {
		return this.def120;
	}

	public void setDef120(String def120) {
		this.def120 = def120;
	}

	public String getDef121() {
		return this.def121;
	}

	public void setDef121(String def121) {
		this.def121 = def121;
	}

	public String getDef122() {
		return this.def122;
	}

	public void setDef122(String def122) {
		this.def122 = def122;
	}

	public String getDef123() {
		return this.def123;
	}

	public void setDef123(String def123) {
		this.def123 = def123;
	}

	public String getDef124() {
		return this.def124;
	}

	public void setDef124(String def124) {
		this.def124 = def124;
	}

	public String getDef125() {
		return this.def125;
	}

	public void setDef125(String def125) {
		this.def125 = def125;
	}

	public String getDef126() {
		return this.def126;
	}

	public void setDef126(String def126) {
		this.def126 = def126;
	}

	public String getDef127() {
		return this.def127;
	}

	public void setDef127(String def127) {
		this.def127 = def127;
	}

	public String getDef128() {
		return this.def128;
	}

	public void setDef128(String def128) {
		this.def128 = def128;
	}

	public String getDef129() {
		return this.def129;
	}

	public void setDef129(String def129) {
		this.def129 = def129;
	}

	public String getDef130() {
		return this.def130;
	}

	public void setDef130(String def130) {
		this.def130 = def130;
	}

	public String getDef131() {
		return this.def131;
	}

	public void setDef131(String def131) {
		this.def131 = def131;
	}

	public String getDef132() {
		return this.def132;
	}

	public void setDef132(String def132) {
		this.def132 = def132;
	}

	public String getDef133() {
		return this.def133;
	}

	public void setDef133(String def133) {
		this.def133 = def133;
	}

	public String getDef134() {
		return this.def134;
	}

	public void setDef134(String def134) {
		this.def134 = def134;
	}

	public String getDef135() {
		return this.def135;
	}

	public void setDef135(String def135) {
		this.def135 = def135;
	}

	public String getDef136() {
		return this.def136;
	}

	public void setDef136(String def136) {
		this.def136 = def136;
	}

	public String getDef137() {
		return this.def137;
	}

	public void setDef137(String def137) {
		this.def137 = def137;
	}

	public String getDef138() {
		return this.def138;
	}

	public void setDef138(String def138) {
		this.def138 = def138;
	}

	public String getDef139() {
		return this.def139;
	}

	public void setDef139(String def139) {
		this.def139 = def139;
	}

	public String getDef140() {
		return this.def140;
	}

	public void setDef140(String def140) {
		this.def140 = def140;
	}

	public String getDef141() {
		return this.def141;
	}

	public void setDef141(String def141) {
		this.def141 = def141;
	}

	public String getDef142() {
		return this.def142;
	}

	public void setDef142(String def142) {
		this.def142 = def142;
	}

	public String getDef143() {
		return this.def143;
	}

	public void setDef143(String def143) {
		this.def143 = def143;
	}

	public String getDef144() {
		return this.def144;
	}

	public void setDef144(String def144) {
		this.def144 = def144;
	}

	public String getDef145() {
		return this.def145;
	}

	public void setDef145(String def145) {
		this.def145 = def145;
	}

	public String getDef146() {
		return this.def146;
	}

	public void setDef146(String def146) {
		this.def146 = def146;
	}

	public String getDef147() {
		return this.def147;
	}

	public void setDef147(String def147) {
		this.def147 = def147;
	}

	public String getDef148() {
		return this.def148;
	}

	public void setDef148(String def148) {
		this.def148 = def148;
	}

	public String getDef149() {
		return this.def149;
	}

	public void setDef149(String def149) {
		this.def149 = def149;
	}

	public String getDef150() {
		return this.def150;
	}

	public void setDef150(String def150) {
		this.def150 = def150;
	}

	public String getDef151() {
		return this.def151;
	}

	public void setDef151(String def151) {
		this.def151 = def151;
	}

	public String getDef152() {
		return this.def152;
	}

	public void setDef152(String def152) {
		this.def152 = def152;
	}

	public String getDef153() {
		return this.def153;
	}

	public void setDef153(String def153) {
		this.def153 = def153;
	}

	public String getDef154() {
		return this.def154;
	}

	public void setDef154(String def154) {
		this.def154 = def154;
	}

	public String getDef155() {
		return this.def155;
	}

	public void setDef155(String def155) {
		this.def155 = def155;
	}

	public String getDef156() {
		return this.def156;
	}

	public void setDef156(String def156) {
		this.def156 = def156;
	}

	public String getDef157() {
		return this.def157;
	}

	public void setDef157(String def157) {
		this.def157 = def157;
	}

	public String getDef158() {
		return this.def158;
	}

	public void setDef158(String def158) {
		this.def158 = def158;
	}

	public String getDef159() {
		return this.def159;
	}

	public void setDef159(String def159) {
		this.def159 = def159;
	}

	public String getDef160() {
		return this.def160;
	}

	public void setDef160(String def160) {
		this.def160 = def160;
	}

	public String getDef161() {
		return this.def161;
	}

	public void setDef161(String def161) {
		this.def161 = def161;
	}

	public String getDef162() {
		return this.def162;
	}

	public void setDef162(String def162) {
		this.def162 = def162;
	}

	public String getDef163() {
		return this.def163;
	}

	public void setDef163(String def163) {
		this.def163 = def163;
	}

	public String getDef164() {
		return this.def164;
	}

	public void setDef164(String def164) {
		this.def164 = def164;
	}

	public String getDef165() {
		return this.def165;
	}

	public void setDef165(String def165) {
		this.def165 = def165;
	}

	public String getDef166() {
		return this.def166;
	}

	public void setDef166(String def166) {
		this.def166 = def166;
	}

	public String getDef167() {
		return this.def167;
	}

	public void setDef167(String def167) {
		this.def167 = def167;
	}

	public String getDef168() {
		return this.def168;
	}

	public void setDef168(String def168) {
		this.def168 = def168;
	}

	public String getDef169() {
		return this.def169;
	}

	public void setDef169(String def169) {
		this.def169 = def169;
	}

	public String getDef170() {
		return this.def170;
	}

	public void setDef170(String def170) {
		this.def170 = def170;
	}

	public String getDef171() {
		return this.def171;
	}

	public void setDef171(String def171) {
		this.def171 = def171;
	}

	public String getDef172() {
		return this.def172;
	}

	public void setDef172(String def172) {
		this.def172 = def172;
	}

	public String getDef173() {
		return this.def173;
	}

	public void setDef173(String def173) {
		this.def173 = def173;
	}

	public String getDef174() {
		return this.def174;
	}

	public void setDef174(String def174) {
		this.def174 = def174;
	}

	public String getDef175() {
		return this.def175;
	}

	public void setDef175(String def175) {
		this.def175 = def175;
	}

	public String getDef176() {
		return this.def176;
	}

	public void setDef176(String def176) {
		this.def176 = def176;
	}

	public String getDef177() {
		return this.def177;
	}

	public void setDef177(String def177) {
		this.def177 = def177;
	}

	public String getDef178() {
		return this.def178;
	}

	public void setDef178(String def178) {
		this.def178 = def178;
	}

	public String getDef179() {
		return this.def179;
	}

	public void setDef179(String def179) {
		this.def179 = def179;
	}

	public String getDef180() {
		return this.def180;
	}

	public void setDef180(String def180) {
		this.def180 = def180;
	}

	// add by zengzw@ 2016年4月22日16:14:34 end

	public static final String PK_TERMITEM = "pk_termitem";
	public static final String EXPIREDATE = "expiredate";
	public static final String ISURGENT = "isurgent";

	private String pk_termitem;
	private UFDate expiredate;
	private UFBoolean isurgent;

	public void setIsurgent(UFBoolean isurgent) {
		this.isurgent = isurgent;
	}

	public UFBoolean getIsurgent() {
		return isurgent;
	}

	public String getPk_termitem() {
		return pk_termitem;
	}

	public void setPk_termitem(String pk_termitem) {
		this.pk_termitem = pk_termitem;
	}

	public UFDate getExpiredate() {
		return expiredate;
	}

	public void setExpiredate(UFDate expiredate) {
		this.expiredate = expiredate;
	}
}
